.asf.yaml

Added similar settings as used in main pulsar repo

Added .asf.yaml file

---

CONTRIBUTING.md
LICENSE
NOTICE
SECURITY.md

Added license and notice files

Added license and notice files

---

.github/workflows/ci-pr-validation.yaml
.gitignore
build-support/generate-source-archive.sh
docker-build-centos7.sh
pkg/apk/.gitignore
pkg/apk/APKBUILD
pkg/apk/build-apk.sh
pkg/apk/docker-build-apk.sh
pkg/deb/build-deb.sh
pkg/deb/docker-build-deb.sh
pkg/rpm/Dockerfile
pkg/rpm/SPECS/pulsar-client.spec
pkg/rpm/build-rpm.sh

Fixed RPM / Deb / APK packages and enabled CI build

Fixed RPM / Deb / APK packages and enabled CI build

---

include/pulsar/ClientConfiguration.h
lib/ClientConfiguration.cc
lib/ClientConfigurationImpl.h
lib/ClientConnection.cc
lib/HTTPLookupService.cc
lib/HTTPLookupService.h
lib/c/c_ClientConfiguration.cc
tests/AuthBasicTest.cc

Add a TLS transport config for the client.
In the old version, we can only use the TLS authentication to config the TLS transport, so we cannot use the other authentication, which is confusing, so we need to add a TLS transport config for the client, which would resolve the issue I mentioned.
When using this config with the TLS authentication, the TLS authentication config is preferred.

Add TLS transport config

---

.github/workflows/ci-build-binary-artifacts.yaml
.github/workflows/ci-pr-validation.yaml
pkg/deb/Dockerfile
pkg/deb/build-deb.sh
pkg/deb/create-images.sh
pkg/deb/docker-build-deb-arm64.sh
pkg/deb/docker-build-deb-x86_64.sh
pkg/rpm/Dockerfile
pkg/rpm/create-images.sh
pkg/rpm/docker-build-rpm-arm64.sh
pkg/rpm/docker-build-rpm-x86_64.sh

When we push a tag, trigger a job that builds RPM/Deb packages for both x86_64 and arm64 and uploads them as artifacts.
The release manager can then fetch the binaries when preparing a release.

Build release artifacts

---

.github/workflows/ci-pr-validation.yaml
lib/ClientConfiguration.cc
lib/checksum/crc32c_arm.h
tests/AuthPluginTest.cc
tests/ProtobufNativeSchemaTest.cc

Enable format check in PR validation

Enable format check in PR validation

---

lib/CMakeLists.txt

Currently, the `pulsarStaticWithDeps` target (`libpulsarwithdeps.a`) is generated under the `./lib` directory relative to the project root path. However, if the cmake build directory is customized, e.g. `cmake -B build`, the `libpulsarwithdeps.a` is still generated under `lib/`, not `build/lib`.
In addition, the install target doesn't install the `libpulsarwithdeps.a` except for MSVC build.
Modify the `lib/CMakeLists.txt` to:
- generate `libpulsarwithdeps.a` under the CMake build directory
- add `libpulsarwithdeps.a` to the install target
Run the following commands:
```bash
cmake -DLINK_STATIC=ON -DCMAKE_INSTALL_PREFIX=/tmp/pulsar-cpp -B build
cmake --build build --target install
```
We can see the following files generated and installed:
```bash
$ ls -1 build/lib/libpulsar* …
```

Generate and install pulsarStaticWithDeps into correct paths

---

README.md

For the new repo, we don't need cd to `${PULSAR_PATH}` when building, so we can remove the `${PULSAR_PATH}`.
Remove `${PULSAR_PATH}`.

[fix] Fix README.md build path

---

include/pulsar/c/consumer_configuration.h
lib/c/c_ConsumerConfiguration.cc
tests/c/c_ConsumerConfigurationTest.cc

Expose start message id inclusive configuration to C API
* Expose `start_message_id_inclusive` to C API.
* Add unit tests for C API of producer configuration and consumer configuration.

[feat] Expose start message id inclusive configuration to C API

---

CMakeLists.txt

There is an extra call to `find_package(OpenSSL)` that will make cmake to fail on MacOS since the non-standard paths are not specified yet.

Removed extra call of `find_package(OpenSSL)`

---

docker-build.sh
docker-format.sh
docker-tests.sh

Currently, the `docker-*.sh` are using the incorrect project root path. Need to fix thems.
* Fix the incorrect path
We need to add `git config --global --add safe.directory /pulsar-client-cpp` to the `docker-test.sh` otherwise it will throw:
```
fatal: unsafe repository ('/pulsar-client-cpp' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /pulsar-client-cpp
```
This started appearing with the release of the Git 2.35.2 security update which fixes vulnerabilities described [here](https://github.blog/2022-04-12-git-security-vulnerability-announced/). [FYI](https://stackoverflow.com/questions/71901632/fatal-error-unsafe-repository-home-repon-is-owned-by-someone-else)
This change is a trivial rework / code cleanup without any …

Fix incorrect path in docker scripts

---

.asf.yaml

Currently,  there is no required workflow for the PR.
Enable required check status for pr validation

Enable required check status for PR validation

---

README.md

Fixes https://github.com/apache/pulsar/issues/17427
The compilation guidance on Ubuntu is wrong, we must copy the `gmock` directory into `/usr/include` to avoid `GMOCK_INCLUDE_PATH` is not found.
- Copy the `gmock` directory into `/usr/include`
- Make it clear the directory of `*.a` is `lib/` because the guidance specify Ubuntu 20.04 as the OS.
- Remove unnecessary dependencies

[docs] Fix compilation guidance on Ubuntu

---

.asf.yaml

Currently, in workflow, the unit tests job is not required. 
Enable required check status for unit tests job.

Enable required check status for unit tests job

---

include/pulsar/Authentication.h
lib/Authentication.cc
lib/auth/AuthBasic.cc
lib/auth/AuthBasic.h
tests/AuthBasicTest.cc

Added option to set the method name for Basic authentication

Added option to set the method name for Basic authentication

---

pkg/apk/Dockerfile

Use Alpine 3.12 to build APKs instead of 3.16 as it could link with symbols that are not available on manylinux images

Use Alpine 3.12 to build APKs

---

.asf.yaml
.github/workflows/ci-pr-validation.yaml

The definition for required CI jobs is set into `.asf.yaml` file though that file is synced in background and only after a PR is committed. 
That makes it difficult to add or rename CI jobs because these PRs won't be passing the validation.
Instead, use a simple check-completion jobs that will be the only required job, though it waits for all the others to finish

Improved the CI check completion

---

README.md

Currently, some build guide is out-of-date. We need to update the build guide.
The first issue is when we install the dependencies for Ubuntu, we still need manually compile and install google test and google mock. 
However, we can use `libgmock-dev` to replace the `google-mock`, since the `libgmock-dev` already contains the static-link library.
```
$ dpkg -L libgmock-dev
// ...
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libgmock.a
/usr/lib/x86_64-linux-gnu/libgmock_main.a
// ...
```
Same as the `libgtest-dev`.
```
$ dpkg -L libgtest-dev
// ...
/usr/lib/x86_64-linux-gnu/libgtest.a
/usr/lib/x86_64-linux-gnu/libgtest_main.a
// ...
```
The second issue is macOS dependency. The `boost-python` has already been removed from the brew core. We should always use `boost-python3`.
```
~ …
```

Fix Ubuntu and macOS build guide

---

.github/workflows/ci-build-binary-artifacts.yaml
.github/workflows/ci-pr-validation.yaml

Some of the GH actions versions we are using have just been deprecated. Changing to use the latest versions.

Updated Github actions versions to avoid deprecations

---

lib/NamedEntity.cc
tests/NamespaceNameTest.cc
tests/TopicNameTest.cc

C++ client is not allowing some characters like `:` in the cluster or namespace names. This is not consistent with Java client and the broker validations which allow such character. 
We must use the same exact logic of validation for topic names as in https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/java/org/apache/pulsar/common/naming/NamedEntity.java

Fixed validation of cluster/namespace names containing legal non-alpha characters

---

include/pulsar/BatchReceivePolicy.h
include/pulsar/Consumer.h
include/pulsar/ConsumerConfiguration.h
lib/BatchReceivePolicy.cc
lib/BatchReceivePolicyImpl.h
lib/ClientImpl.h
lib/Consumer.cc
lib/ConsumerConfiguration.cc
lib/ConsumerConfigurationImpl.h
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/ConsumerImplBase.cc
lib/ConsumerImplBase.h
lib/HandlerBase.h
lib/MessagesImpl.cc
lib/MessagesImpl.h
lib/MultiTopicsConsumerImpl.cc
lib/MultiTopicsConsumerImpl.h
tests/BasicEndToEndTest.cc
tests/BatchReceivePolicyTest.cc
tests/ConsumerConfigurationTest.cc
tests/MessagesImplTest.cc

https://github.com/apache/pulsar/issues/17140
This PR has been reviewed in [pulsar repo](https://github.com/apache/pulsar/pull/17429).
- Consumer support batch receives messages.
- Abstract common implementation to `ConsumerImplBase`.
https://github.com/shibd/pulsar-client-cpp/pull/1

[feat] Consumer support batch receive messages.

---

tests/ProducerTest.cc
tests/ShutdownTest.cc

Fixes #58 #24
gtest-parallel runs tests in different processes, not threads. So the topic name could be the same even if it has the timestamp suffix. Then `ConsumerBusy` error would occur.
In each `TEST_P` method, convert `GetParam()` to a unique string to avoid topic conflict.

[flaky-test] Fix very flaky tests for TEST_P

---

.github/workflows/ci-build-binary-artifacts.yaml

Because of the typo in the variable name, the packages end up with the same name for both x86_64 and arm64 and GH action is merging them. It's mainly a problem for Deb packages since the files don't have the arch in the file names.

Fixed the release artifacts package file name

---

tests/ShutdownTest.cc
tests/WaitUtils.h

Fixes #61
`testDestructor` is flaky because the destructor might not be called immediately after the `shared_ptr` object goes out of the scope. It's similar like the flaky `testReferenceCount` before in https://github.com/apache/pulsar/pull/17645.
Add back `WaitUtils.h`, which was removed in #55, add use `waitUntil` to wait until the assertion.
Run the reproduce script in #61. Even if the loop count was increased to 100, it still never failed.

[flaky tests] Fix flaky ShutdownTest::testDestructor

---

lib/ProducerImpl.h

In macOS, the value type of STL container cannot be forward declared

Fix macOS compilation errors caused by forward declaration

---

README.md

[fix][doc] explicitly instruct clone the repo

---

include/pulsar/Consumer.h
include/pulsar/MessageId.h
lib/AckGroupingTracker.h
lib/AckGroupingTrackerEnabled.cc
lib/AckGroupingTrackerEnabled.h
lib/Consumer.cc
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/ConsumerImplBase.h
lib/MultiTopicsConsumerImpl.cc
lib/MultiTopicsConsumerImpl.h
lib/UnAckedMessageTrackerDisabled.h
lib/UnAckedMessageTrackerEnabled.cc
lib/UnAckedMessageTrackerEnabled.h
lib/UnAckedMessageTrackerInterface.h
lib/stats/ConsumerStatsBase.h
lib/stats/ConsumerStatsDisabled.h
lib/stats/ConsumerStatsImpl.cc
lib/stats/ConsumerStatsImpl.h
tests/BasicEndToEndTest.cc
tests/PulsarFriend.h

https://github.com/apache/pulsar-client-cpp/issues/90
- Add acknowledge message id list API.
https://github.com/shibd/pulsar-client-cpp/pull/3

[feat] Support acknowledging a list of messages

---

lib/ConsumerImpl.cc
tests/ConsumerTest.cc

Currently, the consumer will receive old messages after the seek operation. Because the consumer doesn't clear the incomingMessageQueue before reconnecting. Therefore the consumer will dispatch some old messages to the user after the seek operation.
This issue can be easily reproduced by advancing the process of creating consumers to before producing message in `testSeekForMessageId`.
* Clear the incomingMessageQueue after seeking complete.
*(Please pick either of the following options)*
This change is already covered by existing tests, such as *testSeekForMessageId*.

[fix] Fix consumer doesn't clear incomingMessageQueue during seek

---

lib/OpSendMsg.h
lib/ProducerImpl.cc
tests/ProducerTest.cc

#51
- when calling `producer.flush`, wait for no batch message send suceese. 

[fix] Flush no batch message when call producer.flush

---

include/pulsar/Message.h
lib/Message.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/107
The `MessageId::getDataAsString()` API returns a `std::string` to the application side. In most cases it's not an issue. However, when building Windows DLLs with `LINK_STATIC=ON`, the library will be built with `/MTd` or `/MT` option to link 3rd party dependencies statically. In this case, the DLL and the application have different C runtime libraries that allocate or deallocate memory. The returned `std::string` object is allocated inside the DLL, while it will be destroyed in the application for debug build because RVO is not applied. The destruction could crash because the application C runtime cannot find the heap address from the C runtime in DLL.
For MSVC debug build, change the API to return a const reference to …

Fix MessageId::getDataAsString() crashed with MSVC debug config

---

include/pulsar/ProducerConfiguration.h
lib/ClientConnection.cc
lib/ClientConnection.h
lib/HandlerBase.cc
lib/HandlerBase.h
lib/ProducerImpl.cc
tests/ProducerTest.cc

#95 
- Support WaitForExclusive producer access mode.
**Note**: `ExclusiveWithFencing` needs to depend on pulsar to release 2.11

[feat] Support WaitForExclusive producer access mode.

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
tests/MessageChunkingTest.cc

Fixes #104
Currently, the consumer ack the last message when the chunked messages exceed maxPendingChunkMessages. This is wrong behavior. This may lead to unexpected data loss.
This PR also fixes serval issues related to maxPendingChunkedMessages:
https://github.com/apache/pulsar-client-cpp/blob/1f7fdb86c409c1486d160528137f10ce07dcf3b2/lib/ConsumerImpl.cc#L387-L407
In the current logic, there are two `putIfAbsent` operations here, and they are confusing. If a new chunk message is received, it will be added to the chunkedMessageCache. But if the size of the cache reaches the maxPendingChunkedMessages, it will remove at least 1 ctx from the cache due to `chunkedMessageCache_.size() - maxPendingChunkedMessage_ + 1`. But the message is then put into the cache again. This can lead to …

[fix] Fix wrong behavior when removing the chunkedMessageCtx

---

include/pulsar/MessageId.h
include/pulsar/MessageIdBuilder.h
lib/BatchAcknowledgementTracker.cc
lib/ClientConnection.cc
lib/Commands.cc
lib/Commands.h
lib/ConsumerImpl.cc
lib/Message.cc
lib/MessageAndCallbackBatch.cc
lib/MessageBatch.cc
lib/MessageId.cc
lib/MessageIdBuilder.cc
lib/MessageIdImpl.h
lib/MessageIdUtil.h
lib/NegativeAcksTracker.cc
lib/ProducerImpl.cc
lib/UnAckedMessageTrackerEnabled.cc
tests/BasicEndToEndTest.cc
tests/BatchMessageTest.cc
tests/ConsumerTest.cc
tests/MessageChunkingTest.cc
tests/MessageIdTest.cc
tests/PulsarFriend.h

Master issue: https://github.com/apache/pulsar-client-cpp/issues/87
To support batch index acknowledgment, we must provide a method to get the batch size of a batched message ID.
Instead of adding another overload constructor to `MessageId`, this PR adds a `MessageIdBuilder` class to construct the `MessageId` in a more elegant way.
The original constructor is counterintuitive because the partition index is the 1st argument.
https://github.com/apache/pulsar-client-cpp/blob/74ef1a01f5c7a4604d251de6d040c433f9bbf56b/include/pulsar/MessageId.h#L47
Therefore, this PR marks it as deprecated and replace all invocations of it with the `MessageIdBuilder` usages.
To verify the `MessageId::batchSize()`, the following tests are modified:
- `BatchMessageTest.testBatchSizeInBytes`: the batch size is …

Add MessageId::batchSize() and the MessageIdBuilder

---

Doxyfile

Doxygen supports darkmode toggle

---

lib/Consumer.cc
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/ConsumerImplBase.h
lib/GetLastMessageIdResponse.h
lib/MultiTopicsConsumerImpl.cc
lib/MultiTopicsConsumerImpl.h
tests/ConsumerTest.cc

There is a problem with the `getLastMessageId` method currently implemented.
It is recursively invoking itself.
https://github.com/apache/pulsar-client-cpp/blob/ad79becf0814a992ad493bc625ba0a489900451f/lib/Consumer.cc#L293-L301
- Let it call the actual implementation.
**Note**:  `MultiTopicConsumer.getLastMessageId()` is not supported for the time being. I will support it later. Supporting `MultiTopicConsumer` requires the implementation of [MultiMessageId](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiMessageIdImpl.java), which requires more thought and design.

Fix getLastMessageId method dead recursion.

---

lib/ConsumerImpl.cc

When I ran the tests of Python wrapper in my local env, I observed a segmentation fault. See the key stacktrace:
```
#3  0x00007ffff6d742c5 in std::unique_lock<std::mutex>::lock() () from /usr/local/lib/python3.8/dist-packages/_pulsar.cpython-38-x86_64-linux-gnu.so
#4  0x00007ffff6d72523 in std::unique_lock<std::mutex>::unique_lock(std::mutex&) ()
from /usr/local/lib/python3.8/dist-packages/_pulsar.cpython-38-x86_64-linux-gnu.so
#5  0x00007ffff67de193 in pulsar::ClientImpl::newRequestId **(this=0x0)** at /home/xyz/github.com/apache/pulsar-client-cpp/lib/ClientImpl.cc:644
#6  0x00007ffff685d2c2 in pulsar::ConsumerImpl::~ConsumerImpl (this=0x7fff9800f9e0, __in_chrg=<optimized out>)
at /home/xyz/github.com/apache/pulsar-client-cpp/lib/ConsumerImpl.cc:116
```
In the destructor of …

Fix segmentation fault during the destruction of ConsumerImpl

---

build-support/download-release-artifacts.py
build-support/stage-release.sh

The debug artifact for the windows system is too large. They are only used for debugging and don't need to include in the release. And it's better to tar the `windows-static` artifact to make it easier to download.
The final result looks like this: https://dist.apache.org/repos/dist/dev/pulsar/pulsar-client-cpp/pulsar-client-cpp-3.1.0-candidate-1/
* Exclude the windows debug artifact in the release
* Tar `windows-static` artifacts in the release.

[improve] Exclude debug artifact in the release and tar the windows artifacts

---

lib/NamedEntity.cc
tests/NamespaceNameTest.cc
tests/TopicNameTest.cc

Namspace name with underscore is valid before but now invalid. This regression caused by #52.
Broker validates NamedEntity using regex `"^[-=:.\\w]*$"`, which actually includes the underscore. Although the comment saying `alphanumeric (a-za-z_0-9) and these special characters -=:` is a bit confusing. But we should not break the actual validation rules used a long time ago.
https://github.com/apache/pulsar/blob/355ba6002fc33b2716f59ca5d3a4fac667ecf3e1/pulsar-common/src/main/java/org/apache/pulsar/common/naming/NamedEntity.java#L30-L33
Make underscore valid in NamedEntity.
This change can covered by existing tests with some modifications, such as NamespaceNameTest.testNamespaceNameLegalCharacters and TopicNameTest.testLegalNonAlphaCharacters.
(Your PR needs to update docs and you will …

[fix] Fix NamedEntity::checkName regression

---

lib/PartitionedProducerImpl.cc
tests/ProducerTest.cc

PartitionedProducerImpl do not close sub-producers properly when any sub-producer creation fails. Continuing to retry creating producer will eventually reach the maximum producer limit. It seems a regression caused by #54. 
When sub-producer creation fails, state_ is set to Failed. PartitionedProducerImpl::closeAsync only do cleanup when state_==Ready and sub-producers do not close when state_==Failed.
https://github.com/apache/pulsar-client-cpp/blob/f0268ecd29a6d0030b7d07379ec609884b4c14ff/lib/PartitionedProducerImpl.cc#L273-L276
Close sub-producers when state != Closed.
test code:
Client client("pulsar://localhost:6650");
Producer producer;
while (true) {
Result result = client.createProducer("persistent://public/default/test", producer);
if (result != ResultOk) {
cerr << "Error …

[fix] Fix PartitionedProducerImpl::closeAsync to close sub-producers properly

---

lib/AckGroupingTracker.cc
lib/AckGroupingTrackerDisabled.cc
lib/AckGroupingTrackerDisabled.h
lib/AckGroupingTrackerEnabled.cc
tests/AcknowledgeTest.cc
tests/BasicEndToEndTest.cc

When `ackGroupingTimeMs` is 0, `AckGroupingTrackerDisabled` will be created to acknowledge messages immediately. However, since the `addAcknowledgeList` method is not implemented in #23, it doesn't work.
Implement `AckGroupingTrackerDisabled::addAcknowledgeList`. Move the protocol version validation from `AckGroupingTrackerEnabled` to the base class `AckGroupingTracker` so that the `doImmediateAck` overload that accepts `std::set<MessageId>` can be reused.
Add testing params to `testAckMsgList` and
`testAckMsgListWithMultiConsumer` so that various `ackGroupingTimeMs` can be verified.

[fix] Fix acknowledge MessageId list does not work when ackGroupingTimeMs is 0

---

.github/workflows/ci-pr-validation.yaml
tests/KeyValueSchemaTest.cc

The `ubuntu:latest` image became `ubuntu:22.04` after https://github.com/actions/runner-images/issues/6399. The GTest is no longer compatible with the current code so the CI failed.
Pass `int` to `TestWithParam` and stick the image version to `ubuntu-22.04` instead of `ubuntu-latest`.

Fix the broken master by the upgrade of GTest

---

lib/ProducerImpl.cc
tests/ProducerTest.cc

Close broker producer created after producer close to prevent producers from keeping alive in broker, and fix a race condition here.
Race condition sequence:
1. prodcuer.start() is called
2. handleCreateProducer() is called, and runs to right before setCnx()
3. closeAsync() is called and returns directly after getCnx() returns nullptr, so no CloseProducer cmd is sent
4. handleCreateProducer() continues
5. Result: Producer is closed and no CloseProducer cmd is sent to broker
* Close broker producer created after producer close
* Use mutex to prevent race condition. handleCreateProducer() and closeAsync() should be low frequency operations and using mutex here should not affect performance.
* Added unit test …

[fix] Close broker producer created after producer close

---

lib/ClientConnection.cc
tests/ClientTest.cc

Fix a crash when closing a connection while connecting.
There are race conditions in ClientConnection. The normal state change is Pending->TcpConnected->Ready and close will change state to Disconnected. In the current code, when close is called right before state changes to TcpConnected or Ready, state is set to Disconnected and then overwritten to TcpConnected or Ready. Then connection is in an error state and subsequence operations may crash.
* Check isClosed() before state changes
* Use lock to access executor_ to avoid data race in handlePulsarConnected()
* Added a unit test ClientTest.testCloseClient
bug fix only
(Docs have been already …

[fix] Fix a crash when closing a connection while connecting

---

lib/ClientConnection.cc
lib/ClientConnection.h
lib/Commands.cc
lib/Commands.h
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/MultiTopicsConsumerImpl.cc
lib/ProducerConfiguration.cc
lib/ProducerConfigurationImpl.h
lib/ProducerImpl.h
lib/ReaderImpl.cc
lib/SynchronizedHashMap.h
lib/Utils.h
tests/SynchronizedHashMapTest.cc

Fixes #134
Master Issue: #<xyz>
Switch to use boost::optional instead self-written Optional class
Remove class Optional in Utils.h and change all usage to boost::optional
*(Please pick either of the following options)*
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
- [ * ] `doc-not-needed` 
This is internal structure, not a public API

Boost optional

---

README.md

When we execute the command according to the README, it will fail with lack of privilege to execute.
* Use sudo when executing `apt-get install` in the README

[fix] Use sudo when executing `apt-get install`

---

README.md

To match the Ubuntu and Windows documentation, I think it makes sense to include cmake in the Homebrew installation line, much like its included in the apt install line for Ubuntu in the README.
Added cmake to the README for Homebrew installation
- [] `doc-not-needed` 

[fix][doc] CMake is added to the Homebrew Mac Installation list

---

lib/BinaryProtoLookupService.cc

Use authoritative argument correctly in BinaryProtoLookupService::findBroker.
In the current code, authoritative field of lookup request is always false. When a bundle is not loaded by any broker, a lookup request with authoritative as false will not trigger broker to load the bundle, and lookup requests will loop between leader broker and the chosen broker. In this case, the lookup will not succeed and result in a large number of lookup requests to the broker as current c++ client do not have lookup redirect limit. If broker return failure after a large number of redirects, chains 
of future will result in a large depth of function calls and may cause the stack to overflow.
https://github.com/apache/pulsar-client-cpp/blob/44f3b5240732a035395ec34b977301435dd0ec71/lib/BinaryProtoLookupServi …

[fix] Use authoritative argument correctly in BinaryProtoLookupService::findBroker

---

include/pulsar/Message.h
include/pulsar/MessageId.h
lib/ChunkMessageIdImpl.h
lib/Commands.cc
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/Message.cc
lib/MessageId.cc
lib/OpSendMsg.h
lib/ProducerImpl.cc
tests/MessageChunkingTest.cc
tests/PulsarFriend.h

Fixes #79
This is the C++ implementation for https://github.com/apache/pulsar/issues/12402
* Add ChunkMessageIdImpl
* Return ChunkMessageId when the Producer produces the chunk message or when the consumer consumes the chunk message.
* In cosumer.seek, use the first chunk message-id of the chunk message-id. This will solve the problem caused by seeking chunk messages. This is also the impact of this PIP on the original business logic.
*(Please pick either of the following options)*
*(or)*
This change is already covered by existing tests, such as *(please describe tests)*.
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment with large …

[feat] PIP 107: Introduce chunk message ID

---

lib/CMakeLists.txt

There is typo for `auxv.h` header when checking `getauxval` symbol
`auvx.h` -> `sys/auxv.h`
trivial CMake fix

[fix] Fix `auxv` detection

---

CMakeLists.txt
README.md

Currently the released libraries don't hide the symbols from the dependencies, it can be verified by the following steps on Ubuntu:
```bash
curl -O -L https://archive.apache.org/dist/pulsar/pulsar-client-cpp-3.1.0/deb-x86_64/apache-pulsar-client.deb
apt install ./apache-pulsar-client.deb
nm -D /usr/lib/libpulsar.so | grep curl
```
You will see lots of symbols from libcurl are included in `libpulsar.so`:
```
0000000000709f50 T curl_easy_cleanup
000000000070a000 T curl_easy_duphandle
...
```
The root cause is that `-Wl,--exclude-libs,ALL` is added as the compile option, but it should work as a link option.
Use `add_link_options` to add `-Wl,--exclude-libs=ALL` as the link option. It seems that `=ALL` should be correct but `,ALL` also works.

[fix][build] Hide non-exported symbols from the dependencies

---

build-support/run_clang_format.py
examples/SampleAsyncConsumerCApi.c
examples/SampleConsumerCApi.c
examples/SampleConsumerListenerCApi.c
examples/SampleProducerCApi.c
examples/SampleReaderCApi.c

Currently, the .c suffix file is not formatted by `clang-format`.
- `clang-format` support format .c suffix file.
- Correct the current .c file style.

Format .c suffix file.

---

.github/workflows/ci-pr-validation.yaml
lib/BatchMessageAcker.h
lib/ConsumerImpl.cc
lib/MessageBatch.cc
lib/MessageId.cc
lib/MessageIdBuilder.cc
tests/MessageIdTest.cc

The serialization and deserialization of `MessageId` became wrong after https://github.com/apache/pulsar-client-cpp/pull/132.
1. The batch size is not serialized.
2. `BatchedMessageIdImpl` could never be deserialized.
The wrong behaviors could lead to a result that all MessageId objects created from deserialization does not have a batch size, which might make `ReaderTest.testReaderOnSpecificMessageWithBatches` fail when the cmake build type is `Debug`. What's worse is that a MessageId created from deserialization is always treated as a `MessageIdImpl`, on which the acknowledgment will have wrong behavior.
Serialize the batch size if it's valid. In deserialization, create a `BatchedMessageIdImpl` when the batch index and the batch size are valid as a batched message.
There is a problem …

[fix] Fix MessageId serialization when it's a batched message

---

include/pulsar/Result.h
lib/ClientConnection.cc
lib/ConnectionPool.cc
lib/Result.cc
tests/ClientTest.cc

Fixes #140
When running produce and consume, and the client calls close, it
shows `ConnectError` in the close method
```
[[127.0.0.1:43644](http://127.0.0.1:43644/) -> [127.0.0.1:6650](http://127.0.0.1:6650/)] Connection closed with
ConnectError
```
* Show `Connection disconnected` just like the java client did instead of `ConnectError` when the client disconnect successfully.
* Add error log for unexpected closed connection.

[fix] Fix log for connection disconnected expectedly

---

examples/CMakeLists.txt
examples/SampleCustomLoggerCApi.c
include/pulsar/c/client_configuration.h
lib/c/c_ClientConfiguration.cc

#137
-  Add interface `pulsar_client_configuration_set_logger_and_level` to support set the log level.

The C API supports setting the log level.

---

include/pulsar/Consumer.h
include/pulsar/ConsumerConfiguration.h
include/pulsar/Message.h
include/pulsar/MessageBuilder.h
include/pulsar/TypedMessage.h
include/pulsar/TypedMessageBuilder.h
lib/ConsumerImpl.cc
lib/MessageBuilder.cc
lib/MultiTopicsConsumerImpl.cc
tests/TypedMessageTest.cc

Pulsar C++ client doesn't support schema yet. It only supports configuring `SchemaInfo` when creating producers or consumers. The main reason is that C++'s templates are processed at the time of compilation. Templatizing `Producer`, `Consumer` or `Message` could expose all internal code.
Currently, users might write the following code for serialization and deserialization:
```c++
producer.send(MessageBuilder().setContent(encode(value)).build());
```
```c++
Message msg;
consumer.receive(msg);
auto value = decode(msg.getData(), msg.getSize());
```
However, the `encode` and `decode` functions are just possible solutions from users, they might use some other interfaces like a class with two virtual methods. There is no way to provide a common interface for serialization and deserialization. …

[feat] Support messages with generic types

---

lib/ClientConnection.cc
lib/ClientConnection.h

Fixes https://github.com/apache/pulsar-client-cpp/issues/167
Here are some debugging info when the segfault happened in `testCloseClient`. The outputs have been trimmed to make them clear.
An example crash at `async_write`:
```
#12 0x00007ffff7496dad in basic_stream_socket<...>::boost::asio::async_write /usr/include/boost/asio/impl/write.hpp:512
#13 0x00007ffff748e003 in ClientConnection::asyncWrite lib/ClientConnection.h:245
#14 0x00007ffff746e0b6 in ClientConnection::handleHandshake (this=0x555555e689d0) lib/ClientConnection.cc:502
```
Another example crash at `async_receive`:
```
#6  0x00007ffff7497247 in basic_stream_socket<...>::async_receive /usr/include/boost/asio/basic_stream_socket.hpp:677
#7  0x00007ffff748e647 in ClientConnection::asyncReceive lib/ClientConnection.h:258
#8 …
```

Fix segfault caused by socket I/O on a closed io_service

---

lib/c/c_Message.cc

Add missing function definitions for `pulsar_message_has_schema_version` and `pulsar_message_get_schemaVersion`.

[fix] Fix missing schema related function definitions

---

include/pulsar/ConsumerConfiguration.h
lib/AckGroupingTracker.cc
lib/AckGroupingTrackerEnabled.cc
lib/BatchMessageAcker.h
lib/BatchedMessageIdImpl.h
lib/BitSet.h
lib/Commands.cc
lib/Commands.h
lib/ConsumerConfiguration.cc
lib/ConsumerConfigurationImpl.h
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/MessageIdImpl.h
lib/MessageIdUtil.h
test-conf/standalone-ssl.conf
tests/AcknowledgeTest.cc
tests/BitSetTest.cc
tests/ConsumerConfigurationTest.cc
tests/ConsumerWrapper.h

Fixes https://github.com/apache/pulsar-client-cpp/issues/87
- Add an consumer configuration `setBatchIndexAckEnabled` to enable the batch index ACK. When it's enabled, passing the original `MessageId` instead of the `MessageIdImpl` that trunks the batch index to the ACK grouping tracker.
- Since now a `BatchedMessageIdImpl` could be accepted in the ACK grouping tracker, fix the compare logic.
- Support passing a `BitSet` in `Commands::newAck` and get the internal `BitSet` from `MessageId` in `Commands::newMultiMessageAck`.
- Skip the acknowledged batch indexes when receiving batched messages in `ConsumerImpl::receiveIndividualMessagesFromBatch`.
Modify `BitSetTest.testSet` to verify the `BitSet::get` method added in this commit.
Add `AcknowledgeTest.testBatchIndexAck` to test batch index …

[feat] Support batch index acknowledgment

---

lib/BatchMessageAcker.h

Currently the main branch is broken by the concurrent merge of https://github.com/apache/pulsar-client-cpp/pull/153 and https://github.com/apache/pulsar-client-cpp/pull/151.
Add a dummy `getBitSet` implementation to `BatchMessageAcker` and the correct implementation for `BatchMessageAckerImpl`.

Fix broken main branch caused by wrong getBitSet method

---

include/pulsar/Reader.h
include/pulsar/ReaderConfiguration.h
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/ConsumerImplBase.h
lib/MultiTopicsConsumerImpl.cc
lib/MultiTopicsConsumerImpl.h
lib/Reader.cc
lib/ReaderImpl.cc
lib/ReaderImpl.h
tests/ReaderTest.cc

Currently, Reader does not support the `readNextAsync ` interface. 
- Modify the  `Consumer:receiveAsync` method to pass the parameter callback reference to pass as a value.
- Add  `readNextAsync ` interface and Impl to `Reader`.
- Add `ReaderTest.testAsyncRead` to cover this change.

[feat] Reader support readeNextAsync interface.

---

include/pulsar/ConsumerConfiguration.h
include/pulsar/DeadLetterPolicy.h
include/pulsar/DeadLetterPolicyBuilder.h
include/pulsar/ProducerConfiguration.h
lib/Commands.cc
lib/Commands.h
lib/ConsumerConfiguration.cc
lib/ConsumerConfigurationImpl.h
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/DeadLetterPolicyBuilder.cc
lib/DeadLetterPolicyImpl.cc
lib/DeadLetterPolicyImpl.h
lib/MessageIdImpl.h
lib/MultiTopicsConsumerImpl.cc
lib/NegativeAcksTracker.cc
lib/ProducerConfigurationImpl.h
lib/ProducerImpl.cc
tests/ConsumerConfigurationTest.cc
tests/DeadLetterPolicyTest.cc
tests/DeadLetterQueueTest.cc
tests/PulsarFriend.h

Master Issue: #114 
#77, #114 
-  Add DeadLetterPolicy. When the message `redeliveryCount > DeadLetterPolicy.maxRedeliveryCount`, the message is sent to the DLQ topic and ack this msg.
1. Add DeadLetterQueueTest to verify Send to DLQ, according to the following scenarios(Cartesian product of the following conditions): 
- Producer batch [enabled, disable]
- Topic is [single, multi]
- Consumer sub type [Shared, Key_Shard]
- Trigger by [unack, ack_timeout]
2. Add `DeadLetterQueueTest.testInitSubscription` to cover init DLQ topic subscription: https://github.com/apache/pulsar/pull/13355
3. Add `DeadLetterQueueTest.testAutoSetDLQTopicName` to cover default DLQ topic name.
4. Add `DeadLetterQueueTest.testDLQWithSchema`  to cover producer …

[feat] Support Dead Letter Topic.

---

wireshark/CMakeLists.txt
wireshark/README.md
wireshark/pulsarDissector.cc

* Fixes #181
* Fixes #179
* Fixes #180
The Pulsar Wireshark plugin has not been maintained for a long time, 
the Pulsar protobuf command and Wireshark header file have been updated.
1. Fix protobuf file path
2. Fix the Wireshark header
3. Fix README base path

Fix Wireshark build

---

lib/ClientImpl.cc
lib/ConsumerImpl.h
lib/ConsumerImplBase.h
lib/MultiTopicsConsumerImpl.cc
lib/MultiTopicsConsumerImpl.h
lib/ReaderImpl.cc
lib/ReaderImpl.h
lib/UnAckedMessageTrackerEnabled.h
tests/ConsumerTest.cc
tests/PulsarFriend.h
tests/ReaderTest.cc

In the current implementation, Reader does not yet support partitioned topics.
- MultiTopicConsumer support `hasMessageAvailable` and `acknowledgeCumulativeAsync` method.
- Reader support partitioned topic.
- Add all tests in `ReaderTest` to multi-partition topic scenarios.
- Add `ConsumerTest.testAcknowledgeCumulativeWithPartition` unit test to cover MultiTopicConsumer.acknowledgeCumulativeAsync method.

[feat] Support partitioned topic reader.

---

lib/AckGroupingTrackerEnabled.cc
lib/AckGroupingTrackerEnabled.h
lib/ConsumerImpl.cc

Avoid resource leakage of AckGroupingTracker.
The result of AckGroupingTracker leakage is waste of cpu. In our case, after a large number (30w+) of consumer creation failures, pulsar client io threads use 99% cpu when no operations.
There are two problems about the leakage:
* In the current code, if consumer creation failed, ConsumerImpl::ackGroupingTrackerPtr_ will not close.
* AckGroupingTrackerEnabled has race condition between close and reschedule, and may continue reschedule after close.
* ConsumerImpl: close ackGroupingTrackerPtr_ when shutdown
* AckGroupingTrackerEnabled: add state, and check state before reschedule
Can verify this change by adding a log and using a test program. The leakage resources are hold in boost::asio::io_service and seems not easy to write a unit test to …

[fix] Avoid resource leakage of AckGroupingTracker

---

lib/ClientConnection.cc
lib/auth/AuthOauth2.cc
lib/auth/AuthOauth2.h
lib/auth/InitialAuthData.h

Fixes https://github.com/apache/pulsar-client-cpp/issues/184
`ClientConfiguration::getTlsTrustCertsFilePath` is only used for HTTP service URL lookup and the TLS handshake, but not used for the OAuth2 client credentials flow. If the issuer URL or the OAuth2 authorization server requires the CA cert, the CA cert can only be loaded from a specific path, which is determined by how to build the C++ client. e.g. it's `/etc/ssl/certs/ca-certificates.crt` when libcurl is built in Debian-based Linux distros and `/etc/pki/tls/certs/ca-bundle.crt` in RedHat-based Linux distros. A typical issue is that the Pulsar Python wheels are built in a [RedHat-based Linux image](https://github.com/pypa/manylinux), if they are installed in a Debian-based Linux distro, users can only fix this issue by copying …

[fix] Use ClientConfiguration::getTlsTrustCertsFilePath for the OAuth2 flow

---

lib/PartitionedProducerImpl.cc
tests/ProducerTest.cc
tests/PulsarFriend.h

Fixes #186
This PR fixes the deadlock issue mentioned in https://github.com/apache/pulsar-client-cpp/issues/186
The case is that when we create a Partitioned Producer with 2 partitions. 
And then we expand the topic to 3 partitions. The PP(Partitioned Producer) will create a new internal producer(Let's called it P3)
But if we close the PP before P3 starts completed. The P3.closeAsync will be called. And it will failed the creation for itself here: https://github.com/apache/pulsar-client-cpp/blob/63c424555cdb1209c82e2f844d7414c1fc399ef8/lib/ProducerImpl.cc#L938
The PP then knows the P3 has failed to create and then close PP.closeAsync again:
https://github.com/apache/pulsar-client-cpp/blob/63c424555cdb1209c82e2f844d7414c1fc399ef8/lib/PartitionedProducerImpl.cc#L164
The internal producers …

[fix] Fix deadlock when closing the partitioned producer

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/NegativeAcksTracker.cc
lib/NegativeAcksTracker.h
tests/ConsumerTest.cc

When consumers close, also need close `NegativeAcksTracker`.
- ConsumerImpl: close `negativeAcksTracker_`(cancel timer and clear nackedMessages_) when consumer shutdown or close.
- Add `ConsumerTest.testNegativeAcksTrackerClose` to cover it.

[Fix] NegativeAcksTracker need close when consumer closed.

---

include/pulsar/ClientConfiguration.h
lib/BinaryProtoLookupService.cc
lib/BinaryProtoLookupService.h
lib/ClientConfiguration.cc
lib/ClientConfigurationImpl.h
lib/ClientImpl.cc
lib/ConsumerImpl.cc
lib/HTTPLookupService.cc
lib/HTTPLookupService.h
lib/HandlerBase.h
lib/PartitionedProducerImpl.cc
lib/ProducerImpl.cc
tests/LookupServiceTest.cc

Master Issue: apache/pulsar#7096
C++ client's `BinaryProtoLookupService` does not limit the times of client's lookup redirection. It may result in broker overloading as described in apache/pulsar#7096.
1. Added max. look redirection limit in `BinaryProtoLookupService::findBroker`.
2. Added configuration to control max times of lookup redirection in both `BinaryProtoLookupService` and `HTTPLookupService`.
3. Added configuration to control initial- and max-backoff interval in both `ProducerImpl` and `ConsumerImpl`.
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*

[improve] Add configuration to limit times of client's lookup redirection.

---

.github/workflows/ci-pr-validation.yaml

https://github.com/apache/pulsar-client-cpp/actions/runs/4220713571/jobs/7327254536
It failed because `pkg-config` is not installed by default after the upgrade of `macos-12` GitHub runner image.
Here is a fix from the upstream: https://github.com/actions/runner-images/pull/7125
Install the `pkg-config` dependency.

Fix broken main branch that failed to build the wireshark dissector on macOS

---

lib/ClientConnection.cc
lib/ClientConnection.h

The C++ Client handles responses in a huge switch block in `ClientConnection::handleIncomingCommand`, which has 553 lines currently. It's not good to maintain since we have some responses to handle in future.
Add a series of `handleXXX` methods to handle responses in `ClientConnection`.

[refactor] Handle responses in methods instead of switch cases

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
tests/ConsumerTest.cc

Master Issue: https://github.com/apache/pulsar/pull/3097
Customers who can't decrypt their message must be given a chance to re-decrypt the message if redelivery is enabled.
- When the decrypted message fails, add to `unAckedMessageTrackerPtr_` to wait for redelivery.
- Added `testRedeliveryOfDecryptionFailedMessages` to cover it.

[fix] Redeliver messages that can't be decrypted.

---

lib/Commands.cc
tests/ClientTest.cc
tests/HttpHelper.cc
tests/HttpHelper.h

Currently,  the `client_version ` only shows the version information. And clients in different languages use their own separate version numbers. This can lead to conflict. For example, the java client 2.10.2 uses the same value `2.10.2` as the C++ client 2.10.2. And C++ client 3.0.0 may conflict with the future java client 3.0.0. The information of `client_version` is incomplete. We could not determine what language(or specific library) the client uses. This raises inconvenience for debugging.
This PR adopts a new client version format for the C++ client.
Please see the discussion: https://lists.apache.org/thread/n59k537fhthjnzkfxtc2p4zk4l0cv3mp
* Change the client version value to `Pulsar-C++-vXXX`
This change added tests.
(Please …

[improve] Refactor client version format

---

CMakeLists.txt
lib/ClientConnection.cc
lib/ClientImpl.cc
lib/ConnectionPool.cc
lib/ExecutorService.cc
lib/ExecutorService.h
lib/MultiTopicsConsumerImpl.cc
lib/PartitionedProducerImpl.cc
lib/PeriodicTask.cc
lib/PeriodicTask.h
lib/ProducerImpl.cc
lib/ProducerImpl.h
lib/RetryableLookupService.h
run-unit-tests.sh
tests/CMakeLists.txt
tests/PeriodicTaskTest.cc
tests/unix/ConnectionFailTest.cc

Fixes #202
When a `deadline_timer` is constructed, `boost::system::system_error` would be thrown if the fd limit is reached. In this case, the following APIs would fail with exception instead of returning a `Result`:
- `createProducer`
- `subscribe`
- `createReader`
P.S. This behavior is not documented in Boost's documents.
Generally, we should not allow exceptions being thrown from those APIs because we return a `Result` to indicate the error. In addition, these exceptions cannot be caught by the wrapper of other languages.
There is a similar issue: https://github.com/apache/pulsar/issues/14582. However, https://github.com/apache/pulsar/pull/14587 only fixes the case when creating a `socket`. The exception from the constructor of `deadline_timer` is not processed.
Handle the exceptions …

[fix] Handle exceptions when creating timers when fd limit is reached

---

include/pulsar/Reader.h
include/pulsar/TableView.h
lib/Client.cc
lib/ClientImpl.cc
lib/ClientImpl.h
lib/MultiTopicsConsumerImpl.cc
lib/SynchronizedHashMap.h
lib/TableView.cc
lib/TableViewImpl.cc
lib/TableViewImpl.h
tests/PulsarFriend.h
tests/TableViewTest.cc

Master Issue: #89
#89 
- Implement all interfaces of `TableView`.
- Add `TableViewTest` to cover all features.

[TableView-2] Implement all interfaces.

---

lib/MultiTopicsConsumerImpl.cc
tests/ClientTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/209
There is a race condition when `Client::close` is called after a `MultiTopicsConsumerImpl` instance is destructed. e.g.
```c++
{
Consumer consumer;
// subscribe multiple topics or partitions
client.subscribe(/* ... */, consumer);
}  // consumer will be destructed after going out of the scope here
client.close();
```
There is a chance that when `client.close()` is called first, the destructor of `consumer` is not called, so `client.consumers_` is not empty and `ClientImpl::closeAsync` will wait until the `MultiTopicsConsumerImpl::closeAsync` completes. Then, in its callback https://github.com/apache/pulsar-client-cpp/blob/242ad770f76655d92c5c1d1abfdee1319ba2ebdc/lib/MultiTopicsConsumerImpl.cc#L482
the original callback …

Fix Client::close might hang forever for a multi-topics consumer

---

tests/TableViewTest.cc

Fixes #215
The root cause is topic name is duplicated.
- Each test uses a separate topic name.

Fix testPublishEmptyValue flaky test.

---

.github/workflows/ci-pr-validation.yaml
lib/ExecutorService.cc
run-unit-tests.sh

Fixes https://github.com/apache/pulsar-client-cpp/issues/209
When the event loop thread is started from `ExecutorService::restart`, there is a chance that `io_service_.run(ec)` returns immediately. In this case, the `ClientConnection::resolver_` that was registered in the IO service could block forever in `async_resolve` method.
In the event loop thread, if the `io_service::run` method is not stopped by `ExecutorService::close`, just call `restart` and `run` again to avoid the event loop thread exits unexpectedly.
Run the `ConnectionFailTest` independently with `--gtest_repeat=20` to avoid it's still flaky.

Fix event loop thread might exit unexpectedly

---

include/pulsar/Message.h
include/pulsar/MessageId.h
lib/BatchMessageContainerBase.h
lib/Commands.cc
lib/ConsumerImpl.cc
lib/ConsumerImplBase.h
lib/HandlerBase.cc
lib/HandlerBase.h
lib/Message.cc
lib/MessageBatch.cc
lib/MessageId.cc
lib/MessageIdImpl.h
lib/MessageImpl.cc
lib/MessageImpl.h
lib/MultiTopicsConsumerImpl.cc
lib/ProducerImpl.cc

`Message` and `MessageId` are exposing `const std::string& getTopic()` method that returns a reference to an internal variable. 
If the consumer is destroyed the message & messageId object will become invalid and calling `getTopic()` will read an invalid memory location.
The current situation is very error prone and can be a bigger problem when using regex subscription, since a topic can be deleted and the consumer will be closed in the background.
Instead of keeping a `std::string&`, changed to use a `std::shared_ptr<std::string>` so that `Message` and `MessageId` instances will be valid regardless of the consumer.

Use shared_ptr for topic name in message ids

---

lib/ConsumerImpl.cc
lib/ProducerImpl.cc
lib/stats/ConsumerStatsBase.h
lib/stats/ConsumerStatsImpl.cc
lib/stats/ConsumerStatsImpl.h
lib/stats/ProducerStatsBase.h
lib/stats/ProducerStatsImpl.cc
lib/stats/ProducerStatsImpl.h

The timers' callbacks in `ProducerStatsImpl` and `ConsumerStatsImpl` are not thread safe because they both capture the `this` pointer, while when the callback is called in the event loop, `this` might point to an expired instance.
- Capture the weak pointer instead of `this` in these callbacks. Since we cannot call `shared_from_this()` in the constructor, a `start()` method is added.
- Remove the useless `executor_` field and unnecessary null check for `timer_`.

Make stats timers thread safe to use

---

tests/TableViewTest.cc

Fixes #212
This test is intended to cover that it is possible to close during asynchronous creation. But this can be a lot of cases, so it does not make sense. So I removed that section of the test
- Remove async close table view case.

Fix TableViewTest.testCreateTableView flaky test.

---

include/pulsar/MessageId.h
lib/MessageIdImpl.h
lib/MultiTopicsConsumerImpl.cc
tests/AcknowledgeTest.cc
tests/BasicEndToEndTest.cc

Currently if a `MessageId` does not have a topic name, the `getTopicName` method will dereference a null pointer, which leads to a crash. This case usually happens when an invalid message is acknowledged, like
https://github.com/apache/pulsar-client-cpp/issues/224.
Return the const reference to an empty string in `getTopicName` when the inner topic name field is a null pointer. Then, return `ResultOperationNotSupported` when acknowledging such invalid messages.

Fix possible crash caused by MessageId::getTopicName

---

include/pulsar/ConsumerInterceptor.h
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/ConsumerInterceptors.cc
lib/ConsumerInterceptors.h
lib/NegativeAcksTracker.cc
tests/InterceptorsTest.cc

This PR is the C++ implementation of https://github.com/apache/pulsar/pull/3962
* Add `onNegativeAcksSend` to the consumer interceptor
This change added tests.

[feat] Add `onNegativeAcksSend` to the consumer interceptor

---

tests/InterceptorsTest.cc

Fixes #229
Using `time(nulltpr)` is not enough for generating the unique topic name. Especially when running a test for less than a second.
* Use `unique_str` to generate the topic name in ConsumerInterceptorsTest

[fix] Use unique topic name in ConsumerInterceptorsTest

---

include/pulsar/ConsumerConfiguration.h
lib/AckGroupingTracker.cc
lib/AckGroupingTracker.h
lib/AckGroupingTrackerDisabled.cc
lib/AckGroupingTrackerDisabled.h
lib/AckGroupingTrackerEnabled.cc
lib/AckGroupingTrackerEnabled.h
lib/ClientConnection.cc
lib/ClientConnection.h
lib/ClientImpl.cc
lib/ClientImpl.h
lib/Commands.cc
lib/Commands.h
lib/ConsumerConfiguration.cc
lib/ConsumerConfigurationImpl.h
lib/ConsumerImpl.cc
tests/AcknowledgeTest.cc
tests/BasicEndToEndTest.cc
tests/ConsumerConfigurationTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/102
Add a consumer configuration to set `ackReceiptEnabled`, if it's true, when sending a CommandAck request, generate the request id and set the `request_id` field so that the broker will respond with a `CommandAckResponse`. Here we pass the shared pointer to an atomic integer so that we no longer need to hold a weak pointer to `ClientImpl`.
Pass the user-defined callback to the ACK grouping tracker, when the `ackReceiptEnabled` is true, trigger the callback only after receiving the ACK response.
- Add `testAckReceiptEnabled` to verify when `ackReceiptEnabled` is true, the callback will be triggered after `ackGroupingMaxTime`.
- Support configuring `ackReceiptEnabled` for existing `TEST_P` parameterized tests in `AcknowledgeTest`. …

Support waiting for the ACK response

---

tests/InterceptorsTest.cc

After discussed with @BewareMyPower and @shibd , there is a permit issue with the zero queue consumer. The permit for the zero queue consumer may somehow be greater than 1 and cause the test stuck. 
* Remove the zero queue case in ConsumerInterceptorTest to unblock the flaky test first. We will add back the case if the issue is fixed.

[fix][flaky] Remove zero queue case in ConsumerInterceptorTest to reduce flaky

---

lib/AckGroupingTracker.h
tests/ConsumerTest.cc

#232 change interface of `AckGroupingTracker` default impl. 
When ack to the non-persistent topic, callback never be called.
- Default call to callback.
- Add `testAckNotPersistentTopic` to cover it.

Fix ack non-persistent topic will be blocked.

---

include/pulsar/ConsumerConfiguration.h
include/pulsar/RegexSubscriptionMode.h
lib/BinaryProtoLookupService.cc
lib/BinaryProtoLookupService.h
lib/ClientConnection.cc
lib/ClientConnection.h
lib/ClientImpl.cc
lib/ClientImpl.h
lib/Commands.cc
lib/Commands.h
lib/ConsumerConfiguration.cc
lib/ConsumerConfigurationImpl.h
lib/HTTPLookupService.cc
lib/HTTPLookupService.h
lib/LookupService.h
lib/MultiTopicsConsumerImpl.h
lib/PatternMultiTopicsConsumerImpl.cc
lib/PatternMultiTopicsConsumerImpl.h
lib/ProtoApiEnums.h
lib/RetryableLookupService.h
lib/TopicName.cc
lib/TopicName.h
test-conf/standalone-ssl.conf
tests/ConsumerTest.cc
tests/LookupServiceTest.cc
tests/TopicNameTest.cc

Master Issue: #204 
The current default only lookup persistent topics on the namespace, We need to add `RegexSubscriptionMode` to control the lookup topics type.
The Java client relate impl refer: https://github.com/apache/pulsar/pull/2025
- Add `RegexSubscriptionMode` to support pattern subscribe `all/persistent only/non-persistent-only` topic.
- Disable system topic. 
- `TopicNameTest.testRemoveDomain` to cover the newly added `TopicName::removeDomain` method.
- `TopicNameTest.testContainsDomain` to cover the newly added `TopicName::containsDomain` method.
- Refactor `LookupServiceTest.basicGetNamespaceTopics` method to cover more get topics cases.
- `ConsumerTest.testPatternSubscribeTopic` to cover use pattern subscribe to `persistent topic`, `non-persistent topic`, and `all topic`. …

[feat] Support pattern subscribe non-persistent topic.

---

lib/BlockingQueue.h
lib/ConsumerImpl.cc
lib/MultiTopicsConsumerImpl.cc
lib/UnboundedBlockingQueue.h
tests/BasicEndToEndTest.cc
tests/BlockingQueueTest.cc
tests/UnboundedBlockingQueueTest.cc

Currently, the batch receive method may cause data loss.
The root cause is, when `peekMsg` can't add to `messages`(The batch has satisfied the batch receive policy), it has actually been popped.
https://github.com/apache/pulsar-client-cpp/blob/ba7f59d2bb28b72fa6d1d01abada71090537b45e/lib/ConsumerImpl.cc#L652-L657
- Peek first, pop only when it can be added.
- Change `testBatchReceive` test to cover this case: 
Send 100 messages first, batch receive 10 messages at a time, and assert that all messages can be received.

[fix] Consumer batch receive will cause data loss.

---

include/pulsar/c/producer_configuration.h
lib/c/c_ProducerConfiguration.cc
tests/c/c_ProducerConfigurationTest.cc

Support set producer access mode for C client.
- Add get and set producer access mode method.
- `C_ProducerConfigurationTest ` to cover set and get producer access mode, other features are covered by C++ unit tests.

[feat] Support set producer access mode for C client.

---

lib/Log4cxxLogger.cc

When I tried to compile with the USE_LOG4CXX option ON, it failed with the following error:
```
/pulsar-client-cpp/lib/Log4cxxLogger.cc: In static member function 'static log4cxx::LevelPtr pulsar::Log4CxxLogger::getLevel(pulsar::Logger::Level)':
/pulsar-client-cpp/lib/Log4cxxLogger.cc:63:5: error: control reaches end of non-void function [-Werror=return-type]
}
^
```
The reason seems to be that there is no `default` branch in the `switch` statement in `Log4CxxLogger::getLevel`, and control may reach the end of the function without returning anything.
https://github.com/apache/pulsar-client-cpp/blob/872f8abaade7ecd346d3f59e2f6b3901c65ef7de/lib/Log4cxxLogger.cc#L52-L63
Added the `default` branch to the `switch` statement. This branch returns INFO.
(Your PR needs to update docs and you will …

[fix] Fix compilation error that occurs when USE_LOG4CXX is ON

---

build-support/start-mim-test-service-inside-container.sh
build-support/start-test-service-inside-container.sh

It took too much time to start Pulsar standalone for tests because of the slow JVM startup when running `pulsar-admin` commands.
Use `curl` to send REST requests directly. After this change, the startup time reduced from 1m39.597s to 32.451s in my local env.

Speed up the process to start standalone for tests

---

include/pulsar/c/consumer_configuration.h
lib/c/c_ConsumerConfiguration.cc
tests/c/c_ConsumerConfigurationTest.cc

Support set batch index ack for C client.
- Add get and set batch index ack enabled method.
- `C_ConsumerConfigurationTest`  to cover set and get batch index ack enabled, other features are covered by C++ unit tests.

[feat] Support set batch index ack for C client.

---

include/pulsar/c/consumer_configuration.h
lib/c/c_ConsumerConfiguration.cc
tests/c/c_ConsumerConfigurationTest.cc

- Support set consumer regex subscription mode for C client.
- Add get and set `pulsar_consumer_regex_subscription_mode` method.
- C_ConsumerConfigurationTest to cover set and get `pulsar_consumer_regex_subscription_mode`, other features are covered by C++ unit tests.

[feat] Support set consumer regex subscription mode for C client.

---

.github/workflows/ci-pr-validation.yaml
lib/Base64Utils.h
lib/ProtobufNativeSchema.cc
lib/auth/AuthOauth2.cc
lib/auth/AuthOauth2.h
run-unit-tests.sh
test-conf/cpp_credentials_file.json
tests/Base64Test.cc
tests/CMakeLists.txt
tests/oauth2/Oauth2Test.cc
tests/oauth2/docker-compose.yml

Fixes https://github.com/apache/pulsar-client-python/issues/101
Currently the `private_key` field of the JSON passed to `AuthOauth2` only represents the path to the file, we need to support passing the base64 encoded JSON string.
- Add the util methods `encode` and `decode` in namespace `pulsar::base64` for base64 serialization.
- Support the following URL representations for `private_key`:
1. `file:///path/to/key/file`
2. `data:application/json;base64,xxxx`
- Add `Oauth2Test` and set up the test environment for it independently with a Docker compose file.

Support the base64 encoded credentials for OAuth2 authentication

---

include/pulsar/c/consumer.h
include/pulsar/c/messages.h
lib/c/c_Consumer.cc
lib/c/c_Messages.cc
lib/c/c_structs.h
tests/c/c_ConsumerTest.cc

This is the 1st PR to support the batch receive feature for C APIs.
- Add the `pulsar_messages_t` struct to represent a list of messages
- Add the `pulsar_messages_get` and `pulsar_messages_size` functions to traverse all messages in `pulsar_messages_t`
- Add the `pulsar_consumer_batch_receive` function to receive messages in batch and the `pulsar_messages_free` function to free the allocated memory.
- Add `c_ConsumerTest.testBatchReceive` to test batch receive.
There is no memory leak in the test:
```bash
$ valgrind --leak-check=full ./tests/pulsar-tests --gtest_filter='c_ConsumerTest.*'
...
==3019==    definitely lost: 0 bytes in 0 blocks
==3019==    indirectly lost: 0 bytes in 0 blocks
==3019==      possibly lost: 0 bytes in 0 blocks
```
- Batch receive policy
- Asynchronous batch …

[C API] Support synchronous consumer batch receive

---

include/pulsar/ClientConfiguration.h
lib/ClientConfiguration.cc
lib/ClientConfigurationImpl.h
lib/ClientConnection.cc
lib/ClientConnection.h
lib/ClientImpl.cc
lib/ClientImpl.h
lib/Commands.cc
lib/Commands.h
lib/ConnectionPool.cc
lib/ConnectionPool.h
tests/ClientTest.cc
tests/LookupServiceTest.cc

The C++ catch up of [PIP-254](https://github.com/apache/pulsar/issues/19705)
Different from the Java implementation, this PR adds private methods to set or get the description in `ClientConfiguration`. Since `PulsarWrapper` is used as a friend class of nearly all public classes, the 3rd party library that is based on the C++ SDK can set the description by defining a `PulsarWrapper` class.
For the `ConnectionPool` and any `ClientConnection` instance created, store the client version and pass it into `Commands::newConnect`.
Modify the `ClientTest.testClientVersion` to verify the changes.

PIP-254: Support configuring client version with a description suffix

---

include/pulsar/c/consumer.h
include/pulsar/c/consumer_configuration.h
lib/c/c_Consumer.cc
lib/c/c_ConsumerConfiguration.cc
tests/c/c_ConsumerConfigurationTest.cc
tests/c/c_ConsumerTest.cc

Master Issue: #252
Complete batch receive other feature.
- Add batch receive policy.
- Implement asynchronous batch receive.
- Add batch receive async test.

Complete batch receive other feature of C client 

---

include/pulsar/BatchReceivePolicy.h
include/pulsar/c/consumer_configuration.h
lib/c/c_ConsumerConfiguration.cc
tests/c/c_ConsumerConfigurationTest.cc

Currently, the `pulsar_consumer_configuration_get_batch_receive_policy` function returns a struct whose size is greater than 8, which is generally not acceptable in C API design because of the copy overhead.
And the API documents are wrong that they say if the value is less than 0, it means no limit. However, if the value is exactly 0, it also means no limit.
Use the POSIX style for these C APIs. The setter returns -1 if it failed. The getter accepts an output argument to store the value to get.
Then test these changes in `testCApiConfig`. The docs are also fixed.

Improve the C APIs for batch receive policy and fix the wrong documents

---

include/pulsar/c/consumer_configuration.h
lib/c/c_ConsumerConfiguration.cc
tests/c/c_ConsumerConfigurationTest.cc
tests/c/c_ConsumerTest.cc

#114  Support dead letter topic for C client.
- Support pass dead letter topic policy by consumer config of C client.
- Add `testCDeadLetterTopic` to cover simple dlq case(other case cover by C++ test). 
- Enhance `testCApiConfig` to cover config set.

[feat] Support dead letter topic for C client.

---

include/pulsar/Client.h
include/pulsar/Message.h
lib/BinaryProtoLookupService.cc
lib/BinaryProtoLookupService.h
lib/Client.cc
lib/ClientConnection.cc
lib/ClientConnection.h
lib/ClientImpl.cc
lib/Commands.cc
lib/Commands.h
lib/HTTPLookupService.cc
lib/HTTPLookupService.h
lib/Int64SerDes.h
lib/LookupService.h
lib/Message.cc
lib/RetryableLookupService.h
tests/Int64SerDesTest.cc
tests/LookupServiceTest.cc

Currently there is no public API to get the SchemaInfo from the broker. However, when a consumer tries to decode a message of Avro schema, the writer schema that was stored in the broker is required. The C++ client is not responsible to decode the message, but the extended library like the Python client needs the ability to get the writer schema from the broker. There is a workaround that we can send a REST request to query the schema, but it requires the admin permission.
- Add the `Client::getSchemaInfoAsync` method to get the schema info asynchronously. When the schema of the given version does not exist, the `SchemaInfo` whose type is `NONE` will be returned.
- Add the `Message::getLongSchemaVersion` method to get the schema version of a message. The existing `getSchemaVersion` method …

Support get the SchemaInfo from a topic and the schema version

---

include/pulsar/c/reader_configuration.h
lib/c/c_ReaderConfiguration.cc
tests/c/c_ReaderConfigurationTest.cc

Fixes #166 and is a prerequisite for apache/pulsar-client-node#276
This change allows C and derived clients to use end-to-end encryption for Readers.
Exposed the methods that already in the C++ API in the C interface

[feat] Support end-to-end encryption in C Reader API

---

README.md

On README, currently not introduced how to compile `perf`.
-  Introduced how to compile `perf`.

[doc] Fix compile perf on MacOS and Ubuntu.

---

lib/NegativeAcksTracker.cc
lib/NegativeAcksTracker.h
tests/ConsumerTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/265
Make `timer_` const and `enabledForTesting_` atomic in `NegativeAcksTracker` so that the `mutex_` can be used only for the `nackedMessages_` field. After that, we can unlock `mutex_` in `handleTimer` to avoid the potential deadlock from user-provided logger or intercepter.
Add `ConsumerTest.testNegativeAckDeadlock` to verify the fix.

Fix deadlock for negative acknowledgment

---

.github/workflows/ci-pr-validation.yaml
CMakeLists.txt
README.md

Fixes https://github.com/apache/pulsar-client-cpp/issues/268
When users build from source with a dependency that requires a higher C++ version than 11, it will fail because currently the C++ standard is pinned to 11. For example, the latest GTest requires C++14 now. So currently there is no way to build the tests except modifying the CMakeLists.txt file.
Make `CMAKE_CXX_STANDARD` configurable and test it for the macOS workflow because the `gtest` dependency installed from `brew` requires C++14. Add the description into the README for it.

Support specifying the C++ standard for some higher dependencies

---

tests/c/c_ConsumerTest.cc

Master Issue: #270
The root cause is that the client was closed early.
- Removed the error to close the client code. 
- Current unit test failures don't take CI out, and we'll need to look into why.

Fix batch receive for C client unit test faied.

---

lib/auth/athenz/ZTSClient.cc
lib/auth/athenz/ZTSClient.h
tests/ZTSClientTest.cc

- As with the Java client(cf. [apache/pulsar#19445](https://github.com/apache/pulsar/pull/19445)) and Go client(cf. [apache/pulsar-client-go#960](https://github.com/apache/pulsar-client-go/pull/960)), make the AuthAthenz for the cpp client support [Copper Argos](https://github.com/AthenZ/athenz/blob/master/docs/copper_argos.md).
- Add the parameters `x509CertChain` and `caCert` to the ZTSClient.cc. If an X.509 certificate is passed as a parameter, it assumes Copper Argos is used and sets the X.509 certificate as a request parameter to ZTS and gets a RoleToken.
- Remove `tokenExpirationTime` because it is not used for the RoleToken (which is sent to Pulsar Brokers and used for authentication) but for the PrincipalToken (which is only used to get the RoleToken from ZTS). Instead I added …

[improve] AuthAthenz supports Copper Argos

---

lib/ClientConnection.cc
lib/ClientConnection.h
lib/Commands.h
run-unit-tests.sh
tests/CMakeLists.txt
tests/brokermetadata/BrokerMetadataTest.cc
tests/brokermetadata/docker-compose.yml
tests/oauth2/Oauth2Test.cc

pulsar-client-cpp doesn't support parse broker metadata. Which will error whiling connect to  enabledbrokerMetada pulsar.
This PR makes pulsar-client-cpp can consume messages well, but haven't exposing index interface yet.
See also
https://github.com/apache/pulsar-client-go/pull/745
https://github.com/apache/pulsar/blob/e38091044c428af002b16110531497e2abc897d2/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1289

[feat][consumer] Support parse broker metadata

---

README.md

We don't need to install `boost-python3`, which was required for the Python wrapper that is independent now. And the latest `googletest` dependency requires the C++14 support so that we need to pass an extra CMake option for it. See https://github.com/apache/pulsar-client-cpp/pull/269

[docs] Fix the developer guide for macOS users

---

tests/ConsumerTest.cc
tests/SynchronizedQueue.h

Fixes https://github.com/apache/pulsar-client-cpp/issues/280
https://github.com/apache/pulsar/pull/19502 brings a change to the consumer selection of the Failover subscription.
Before that PR, if a new consumer joins a Failover subscription when there is a consumer that subscribes the topic, the new consumer will receive the "inactive" event.
After that PR, a random consumer will receive the "inactive" event.
Change the assertion when `consumer` subscribes the topic with the same subscription.
In addition, use a thread safe queue to avoid race conditions.

Fix flaky testConsumerEventWithoutPartition cause by the change of Pulsar 3.0

---

include/pulsar/Message.h
lib/ClientConnection.cc
lib/Commands.cc
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/Message.cc
lib/MessageImpl.cc
lib/MessageImpl.h
tests/ConsumerTest.cc
tests/brokermetadata/BrokerMetadataTest.cc
tests/brokermetadata/docker-compose.yml

After #276 , We already can consume messages contains index well. Now we can add a method allow user to getIndex.
Index is an optional brokerMetadata. If the index not exists, we will return -1
- Add the assertions to assert the index not equals -1.

[feat][Message] Add getIndex method on Message

---

tests/ProtobufNativeSchemaTest.cc

fixes https://github.com/apache/pulsar-client-cpp/issues/193
`getExternalMessageDescriptor` returns the descriptor of `TestMessage` rather than `ExternalMessage` for Protobuf 3.20.0 or later. And the conditional compilation is meaningless here because `GetDescriptor` is always a static method while it didn't exist for some early versions of Protobuf. The official documentation suggests using `descriptor()`.
Use `descriptor()` method to get the descriptor of a PB class.

Fix testSchemaIncompatibility for Protobuf 3.20.0 or later

---

lib/ClientConnection.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/261
When closing the socket on Windows, the `ERROR_CONNECTION_ABORTED` error might be returned in the callback of `async_receive`. It's caused by the `socket::close` method is not portable enough, see https://www.boost.org/doc/libs/1_81_0/doc/html/boost_asio/reference/basic_stream_socket/close/overload2.html
> For portable behaviour with respect to graceful closure of a connected socket, call shutdown() before closing the socket.
Call `shutdown` in `ClientConnection::closeSocket` before calling `close`. In addition, when no bytes are returned or the `eof` error happened,  print the logs with debug level whatever the error code is in the read callback. …

Close the socket gracefully on Windows

---

.github/workflows/ci-pr-validation.yaml

https://github.com/apache/pulsar-client-cpp/actions/runs/5321241967/jobs/9636098738?pr=287
The root cause is the protobuf release v23.3 last week, which requires the abseil library that is built with C++ 17.
https://github.com/Homebrew/homebrew-core/blob/1a476ad7dc979671b4faf7601ae7d0cb6f39d9cf/Formula/protobuf.rb#L45-L46
- Specify to install protobuf v21.12

Fix ci failed on macos env.

---

lib/ClientImpl.cc
tests/ConsumerTest.cc

When creating a consumer and not set a subscription name, users will receive a `ResutlProducerBusy` result, which is confusing.
```
2023-06-19 08:48:54.412 INFO  [0x7ff84d51c640] Client:90 | Subscribing on Topic :persistent://public/default/test-1
2023-06-19 08:48:54.416 INFO  [0x7ff84d51c640] ClientConnection:184 | [<none> -> pulsar+ssl://v2-10-o.chaos-platform.test.sn2.dev:6651] Create ClientConnection, timeout=10000
2023-06-19 08:48:59.379 INFO  [0x7ff84d51c640] ConnectionPool:106 | Created connection for pulsar+ssl://v2-10-o.chaos-platform.test.sn2.dev:6651
2023-06-19 08:48:59.381 INFO  [0x70000011e000] ClientConnection:382 | [198.18.0.1:52214 -> 198.18.2.113:6651] Connected to broker
2023-06-19 08:49:01.687 INFO  [0x70000011e000] HandlerBase:72 | [0x600001d1a628, , 0] Getting …
```

Fix broker return error code confuse when not set subscription name.

---

include/pulsar/c/message.h
lib/c/c_Message.cc
tests/c/c_MessageTest.cc

Support message copy for C client.
- Add a new method to support the message copy for C client.
- Add c_MessageTest to cover it.

feat: Support message copy for C client.

---

include/pulsar/c/client_configuration.h
tests/c/c_ClientConfigurationTest.cc

The current C for `tls_private_key_file_path` and `tls_certificate_file_path` param only defines the get and set method implementation, not the interface.
- Add get and set interface for `tls_private_key_file_path` and `tls_certificate_file_path`.
- Add `C_ClientConfigurationTest` to cover it.

Add missing tls related method definitions for C client.

---

include/pulsar/ReaderConfiguration.h
lib/ReaderConfiguration.cc
lib/ReaderConfigurationImpl.h
lib/ReaderImpl.cc
tests/ReaderTest.cc

Support configure startMessageIdInclusive for the reader
This change added tests: `ReaderSeekTest::testSeekForMessageId`

[feat] Support configure startMessageIdInclusive for the reader

---

.github/workflows/ci-pr-validation.yaml
CMakeLists.txt
README.md
wireshark/CMakeLists.txt
wireshark/pulsarDissector.cc

The current CMakeLists.txt does not work with the latest Protobuf (23.3.0). It's because currently the Module mode is used to find Protobuf, while the `FindProtobuf.cmake` is not updated to find the Abseil dependency.
See https://github.com/protocolbuffers/protobuf/issues/12292#issuecomment-1529680040
For macOS, use the Config mode to find Protobuf. It's because in other systems, the Module mode works well. Besides, enable `PROTOBUF_USE_DLLS` as a workaround for
https://github.com/protocolbuffers/protobuf/pull/12983 is not released.
Pin the default C++ standard to 17 for macOS so that users don't need to set the C++ standard manually.

Fix build failure with the Protobuf 23.3

---

lib/ConsumerImpl.cc
lib/HandlerBase.cc
lib/HandlerBase.h
lib/ProducerImpl.cc
tests/ConsumerTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/292
When a consumer failed to subscribe due to a retriable error, the time point comparation is wrong:
https://github.com/apache/pulsar-client-cpp/blob/633f4bbe8c182128da09803172676b9d6af05057/lib/ConsumerImpl.cc#L321
`creationTimestamp_ + operationTimeut_` is the deadline, `TimeUtils::now()` is the current time, we should use `>` instead of `<` here to compare them. Otherwise, if the consumer encountered a retriable error and the deadline is not exceeded, the consumer won't reconnect and fail with `ResultRetryable`.
Reverse the comparation between the deadline and the current time. When it times out, completing the future with `ResultTimeout` instead of the `result` itself, which is always `ResultRetryable`.
Add …

Fix retriable errors not handled well when creating producer or consumer

---

lib/PartitionedProducerImpl.cc
tests/PartitionsUpdateTest.cc

When topic update partition, new producer is not created on the new partition. The root is runPartitionUpdateTask not work well. 
runPartitionUpdateTask should be executed next time when partition not updated.

[fix] producer do not create when topic update partition

---

lib/BinaryProtoLookupService.cc
lib/Future.h
lib/stats/ProducerStatsImpl.cc
tests/BasicEndToEndTest.cc
tests/PromiseTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/298
Currently the `Future` and `Promise` are implemented manually by managing conditional variables. However, the conditional variable sometimes behaviors incorrectly on macOS, while the existing `future` and `promise` from the C++ standard library works well.
Redesign `Future` and `Promise` based on the utilities in the standard `<future>` header. In addition, fix the possible race condition when `addListener` is called after `setValue` or `setFailed`:
- Thread 1: call `setValue`, switch existing listeners and call them one by one out of the lock.
- Thread 2: call `addListener`, detect `complete_` is true and call the listener directly.
Now, the previous listeners and the new listener are called concurrently in thread 1 and 2.
Run …

Fix the buggy Future and Promise implementations

---

pulsar-test-service-start.sh

When I run `./pulsar-test-service-start.sh` on macOS m1 13.4, the standalone failed to start due to the wrong permission of the `test-conf` directory that is copied into the container via `docker cp`:
```
I have no name!@a00f70265760:/pulsar$ ls -l | grep test-conf
drwx------ 3  501 dialout  4096 Jun  4 13:31 test-conf
```
It seems to be a bug: https://github.com/docker/for-mac/issues/1814
Execute `docker run` with the current username via `id -u`.

Fix the test script does not work for Docker on macOS

---

include/pulsar/TableView.h
include/pulsar/c/client.h
include/pulsar/c/table_view.h
include/pulsar/c/table_view_configuration.h
lib/c/c_Client.cc
lib/c/c_TableView.cc
lib/c/c_TableViewConfiguration.cc
lib/c/c_structs.h
tests/c/c_TableViewTest.cc

Support table view for C client.
- Add table_view for C client.
- Add table_view_configuration for C client.
- Add CTableViewTest cover it.

feat: Support table view for C client.

---

lib/ClientImpl.cc
lib/LookupService.h
lib/RetryableLookupService.h
lib/RetryableOperation.h
lib/RetryableOperationCache.h
tests/LookupServiceTest.cc
tests/PulsarFriend.h
tests/RetryableOperationCacheTest.cc
tests/TableViewTest.cc

All the retryable operations share the same `Backoff` object in `RetryableLookupService`, so if the reconnection happens for some times, the delay of retrying will keeps the maximum value (30 seconds).
Refactor the design of the `RetryableLookupService`:
- Add a `RetryableOperation` class to represent a retryable operation, each instance has its own `Backoff` object. The operation could only be executed once.
- Add a `RetryableOperationCache` class to represent a map that maps a specific name to its associated operation. It's an optimization that if an operation (e.g. find the owner topic of topic A) was not complete while the same operation was executed, the future would be reused.
- In `RetryableLookupService`, just maintain some caches for different operations.
- Add …

Fix the wrong backoff computation when retrying

---

.github/workflows/ci-pr-validation.yaml
lib/ObjectPool.h
lib/ProducerImpl.cc
lib/ProducerImpl.h
tests/CMakeLists.txt
tests/InterceptorsTest.cc
tests/KeyValueImplTest.cc
tests/LookupServiceTest.cc
tests/MessageChunkingTest.cc
tests/MessageTest.cc
tests/SchemaTest.cc
tests/TableViewTest.cc
tests/c/c_SeekTest.cc

When building the project with the `-DCMAKE_CXX_STANDARD=20` option and GCC 11.3, it failed. There are two main reasons.
One is the `ObjectPool.h`, see http://eel.is/c++draft/diff.cpp17.class#2
In short, see the code below:
```c++
template <typename T>
struct A {
// A<T>() {}  // error: simple-template-id not allowed for constructor
A() {}        // OK, injected-class-name used
};
```
The other reason is deeply hidden and OS-specific. When building the target for the unit test, the `lib/` directory is added into the include directories. So for `#include "Semaphore.h"`, the `Semaphore.h` header will be looked up first in the `lib/` directory. However, C++20 introduced a `<semaphore>` header, which finds the POSIX semaphore header `semaphore.h` in the system path.
For example, the include …

Fix the build failure with C++20 standard

---

lib/BatchMessageContainerBase.cc
lib/ProducerImpl.cc
tests/ProducerTest.cc

When sendAsync batch messages and then flush() and close(), found that the callback of message is ResultAlreadyClosed but not Ok. 
The root is if there is no batch messages remain in BatchMessageContainer when do flush,  the flush callback directly return Ok. Instead, it should return Ok until the lastSendOpFuture complete.  
1. fix the error code.
2. test two cases of flush batch messages.

[fix] callback of send batch message is error when flush

---

lib/ClientConnection.cc
lib/ClientConnection.h
lib/GetLastMessageIdResponse.h

`ClientConnection::newGetLastMessageId` method uses `ClientConnection::sendRequestWithId` one to send request. It adds a new node into `ClientConnection::pendingRequests_` map. However `ClientConnection::handleGetLastMessageIdResponse` method does not affect this map. As a result the size of mentioned map is increased every time when `Reader::getLastMessageIdAsync` method is called.
`ClientConnection::newGetLastMessageId` method uses `ClientConnection::sendCommand` one now to send request.
This change is already covered by existing tests, such as ConsumerTest.testGetLastMessageId and ConsumerTest.testGetLastMessageIdBlockWhenConnectionDisconnected.
- [] `doc-not-needed` 
(Docs have …

[fix][client] Memory leak during GET_LAST_MESSAGE_ID command processing.

---

lib/Commands.cc

When using pulsar tls authentication with a broker that sets the authenticationRefreshCheckSeconds the connection was dropped for each authentication refresh check. After analyzing logs and tcpdumps I concluded that this error appears because the tls authentication is returning no command data, witch does not pass a validation in the broker.
After analyzing the tls auth implementation in Java (that works), I concluded that the authData should always be set, even if the authentication provider does not need.
Broker validation:
https://github.com/apache/pulsar/blob/b69f4efa6058c3f51885a61a2b3acb46f8b730f4/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L897
Golang client also has the same problem:
https://github.com/apache/pulsar-client-go/pull/1062
``` …
```

Fix: client reconnected every authenticationRefreshCheckSeconds when using tls authentication

---

lib/BatchMessageContainer.cc
lib/BatchMessageContainerBase.cc
lib/BatchMessageContainerBase.h
lib/BatchMessageKeyBasedContainer.cc
lib/Commands.cc
lib/Commands.h
lib/MessageAndCallbackBatch.cc
lib/MessageAndCallbackBatch.h
lib/OpSendMsg.h
tests/BatchMessageTest.cc

Currently, each time a message is added to the batch message container,
`serializeSingleMessageInBatchWithPayload` will be called. In this
method, if the payload buffer's size is not enough, it will grow twice.
After batch is cleared, the payload buffer will be reset. For example,
here is a typical buffer size increament during a period of a batch:
```
increase buffer size from 0 to 1033
increase buffer size from 1033 to 2066
increase buffer size from 2066 to 4132
increase buffer size from 3099 to 6198
increase buffer size from 5165 to 10330
increase buffer size from 9297 to 18594
increase buffer size from 17561 to 35122
increase buffer size from 34089 to 68178
increase buffer size from 67145 to 134290
```
Refactor the `MessageAndCallbackBatch` design, in `add` method, only
store the …

Avoid calling serializeSingleMessageInBatchWithPayload each time a message is added

---

lib/HandlerBase.cc
lib/HandlerBase.h

There is a sequence of conditions that can trigger a client to schedule multiple reconnections to the broker. This is due to fact that we're not checking whether such an attempt is already in progress.
example: 
1. Receive `CloseConsumer` command from broker
1a.  Schedule for reconnection in 100ms
2. Connection is closed (eg: broker shutdown has initiated)
2a. Schedule for reconnection in 200ms (since the backoff was already incremented)
Result is that we're going to call `grabCnx()` twice
Use atomic flag to ignore the 2nd attempt, just waiting for the 1st attempt to finish.

Avoid double attempt at reconnecting

---

lib/RetryableOperation.h

Fixes #311 
https://github.com/apache/pulsar-client-cpp/pull/296 introduced a regression for GCC <= 7.
> lib/RetryableOperation.h:109:66: error: 'pulsar::RetryableOperation<T>::runImpl(pulsar::TimeDuration)::<lambda(pulsar::Result, const T&)> [with T = pulsar::LookupService::LookupResult]::<lambda(const boost::system::error_code&)>' declared with greater visibility than the type of its field 'pulsar::RetryableOperation<T>::runImpl(pulsar::TimeDuration)::<lambda(pulsar::Result, const T&)> [with T = pulsar::LookupService::LookupResult]::<lambda(const boost::system::error_code&)>::<this capture>' [-Werror=attributes]
It seems to be a bug for GCC <= 7 abort the visibility of the lambda expression might not be affected by the `-fvisibility=hidden` option.
Add …

Fix the visibility compilation error for GCC <= 7

---

lib/CurlWrapper.h
lib/HTTPLookupService.cc
lib/HTTPLookupService.h
lib/auth/AuthOauth2.cc
lib/auth/athenz/ZTSClient.cc

When libcurl is used in `AuthOauth2`, the `CURLOPT_NOSIGNAL` option is not set, i.e. it will be the default value so that the `Curl_resolv_timeout` function might crash in multi-threading environment.
```
#2 0xf630 in _L_unlock_13 from /lib64/libpthread.so.0 (0x34)
#3 0x2e6c7f in Curl_failf from /usr/local/bin/***/libpulsar.so (0x6f)
#4 0x30a285 in Curl_resolv_timeout from /usr/local/bin/***/libpulsar.so (0x95)
```
Since there are many duplicated code when calling curl C APIs, it's hard to notice that `CURLOPT_NOSIGNAL` is not configured in `AuthOauth2`.
Introduce a `CurlWrapper` class that sets the same options to reduce the duplicated code and adapting consistent behaviors unless a few options.
(Your PR …

[fix] Add the curl wrapper to avoid inconsistent curl options

---

.github/workflows/ci-pr-validation.yaml

Fixes https://github.com/apache/pulsar-client-cpp/issues/314
We need to run `brew update` to have the fix of
https://github.com/Homebrew/homebrew-core/pull/142254 included.

Fix broken wireshark build workflow on macOS

---

lib/BinaryProtoLookupService.cc
lib/ClientConnection.cc
lib/ClientConnection.h
lib/ClientImpl.cc
lib/ClientImpl.h
lib/ConnectionPool.cc
lib/ConnectionPool.h
lib/ConsumerImpl.cc
lib/HandlerBase.cc
lib/HandlerBase.h
lib/ProducerImpl.cc
tests/PulsarFriend.h

We observed server null `ClientConnection` accesses in test environment. See the `this=0x0` outputs in the following two typical stacks.
```
#8  bytesWritten (this=0xb8, size=371) at lib/SharedBuffer.h:166
#9  pulsar::ClientConnection::handleRead (this=0x0, err=..., bytesTransferred=371, minReadSize=4) at lib/ClientConnection.cc:609
```
```
#12 0x00007f33202933d2 in unique_lock (__m=..., this=0x7f3311c82800) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_mutex.h:197
#13 pulsar::ClientConnection::sendPendingCommands (this=0x0) at lib/ClientConnection.cc:1071
#14 0x00007f3320293d2d in pulsar::ClientConnection::handleSendPair (this=0x0, err=...) at lib/ClientConnection.cc:1066
```
Though `shared_from_this()` is always passed to the `std::bind` function, when the method of …

Avoid accessing a null ClientConnection instance

---

lib/ConsumerImplBase.h
lib/HandlerBase.cc
lib/HandlerBase.h
lib/ProducerImpl.cc
lib/ProducerImpl.h

We observed some logs that showed the handler instance is expired when the connection is established after a reconnection:
```
HandlerBase Weak reference is not valid anymore
```
https://github.com/apache/pulsar-client-cpp/blob/b35ae1aa4b9834886c0889635de81834f9b2f774/lib/HandlerBase.cc#L92
Pass a `shared_ptr` instead of a `weak_ptr` in `HandlerBase::grabCnx` to ensure the `connectionOpened` or `connectionFailed` callback is called if `ClientImpl::getConnection` is called. We only need to pass a `weak_ptr` in `scheduleReconnection` to skip the reconnection if the handler is expired.

Fix the handler instance is expired when the connection is established

---

lib/ClientConnection.cc
lib/ClientConnection.h
lib/ConsumerImpl.cc
lib/HandlerBase.cc
lib/ProducerImpl.cc
lib/ResultUtils.h
lib/RetryableOperation.h

When there are multiple pending requests in the same `ClientConnection`, if one request failed with a retryable error, e.g. the `ServiceUnitNotReady` error when finding the owner broker of a topic, the socket will be closed in `checkServerError` and `close()` will be called subsequently in `handleRead` (`err` is `eof` or `operation_failed`). However, the default value of 1st parameter is `ResultConnectError` for `close`, which is not retryable.
If the connection is disconnected by the client, pass `ResultDisconnected` to `close` and treat it as retryable.
`closeSocket` is replaced with `close(ResultDisconnected)` to avoid the connection being the status that socket is closed but TLS stream is not closed.

Fix pending requests failed with ResultConnectError when disconnecting

---

lib/AckGroupingTracker.cc
lib/ChunkMessageIdImpl.h
lib/Commands.cc
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/MessageId.cc
lib/OpSendMsg.h
lib/ProducerImpl.cc
tests/MessageChunkingTest.cc

Fixes #320
Currently, the consumer only acknowledges the last chunk message ID. This will lead to some messages not being acknowledged and the message backlog doesn't get cleaned up.
Add the chunk message Id list into the ChunkedMessageIdImpl. When the consumer acknowledges a chunked message , it will acknowledge all message Ids in that list
This change is already covered by existing tests.

[fix] Fix consumer doesn't acknowledge all chunk message Ids

---

lib/ClientConnection.cc
run-unit-tests.sh
tests/CMakeLists.txt
tests/chunkdedup/ChunkDedupTest.cc
tests/chunkdedup/docker-compose.yml

Fixes https://github.com/apache/pulsar-client-cpp/issues/325
https://github.com/apache/pulsar-client-cpp/pull/317 introduces a bug that might cause segmentation fault when sending messages after receiving an error, see
https://github.com/apache/pulsar-client-cpp/issues/325#issuecomment-1751914150 for the detailed explanation.
When calling `asyncWrite`, capture the `shared_ptr` instead of the `weak_ptr` to extend the lifetime of the `socket_` or `tlsSocket_` field in `ClientConnection`. Since the lifetime is extended, in some callbacks, check `isClosed()` before other logic.
Add a `ChunkDedupTest` to reproduce this issue based on Pulsar 3.1.0. Run the test for 10 times to ensure it won't crash after this patch.

Fix segmentation fault when sending messages after receiving an error

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/MessageCrypto.cc
lib/MessageCrypto.h

`ConsumerImpl::getName()` returns a string that is used in logs to represent the consumer. However, the topic part does not show correctly:
```
ConsumerImpl:283 | [0x6000001c88b8, consumer-1, 0] Created consumer on broker [127.0.0.1:60399 -> 127.0.0.1:6650]
```
It's because after https://github.com/apache/pulsar-client-cpp/pull/218, the `ConsumerImpl::topic_` field becomes `std::shared_ptr` rather than a `std::string` but it is still used to construct the `consumerStr_`.
Construct the `consumerStr_` using the `topic` argument in the constructor and make `consumerStr_` const because it is never changed.
Now the logs will be like:
```
ConsumerImpl:280 | [persistent://public/default/my-topic, consumer-1, 0] Created consumer on broker [127.0.0.1:60647 -> 127.0.0.1:6650]
```

Fix topic not shown correctly in the consumer string

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/ConsumerImplBase.h
lib/Future.h
lib/HandlerBase.cc
lib/HandlerBase.h
lib/ProducerImpl.cc
lib/ProducerImpl.h

Related Issue: https://github.com/apache/pulsar-client-cpp/issues/235
A potential double scheduling of reconnection due to a broker shutdown was observed.
The reconnect can be scheduled with either of the following codes
[ https://github.com/apache/pulsar-client-cpp/blob/b35ae1aa4b9834886c0889635de81834f9b2f774/lib/ConsumerImpl.cc#L1209](https://github.com/apache/pulsar-client-cpp/blob/b35ae1aa4b9834886c0889635de81834f9b2f774/lib/ConsumerImpl.cc#L1209)
or
[ https://github.com/apache/pulsar-client-cpp/blob/b35ae1aa4b9834886c0889635de81834f9b2f774/lib/ClientConnection.cc#L1350](https://github.com/apache/pulsar-client-cpp/blob/b35ae1aa4b9834886c0889635de81834f9b2f774/lib/ClientConnection.cc#L1350)
-> [ https://github.com/apache/pulsar-client-cpp/blob/af45a54c10ec5b06e80b683010afd3531457ac64/l …

Delay the timing of setting reconnectionPending to false to avoid double attempt at reconnecting

---

lib/ClientConnection.cc

https://github.com/apache/pulsar-client-cpp/pull/326 fixes the possible segmentation fault caused by async_write, but it could still crash when triggering the callback of async_receive while the socket is destroyed. See https://github.com/apache/pulsar-client-cpp/issues/324#issuecomment-1767325649
Capture the `shared_ptr` in `asyncReceive`.

Fix segmentation fault caused by async_receive

---

lib/BatchMessageContainerBase.cc
lib/BatchMessageContainerBase.h
lib/ConsumerImpl.cc
lib/HandlerBase.cc
lib/HandlerBase.h
lib/MultiTopicsConsumerImpl.cc
lib/ProducerImpl.cc

This is an additional fix to #329 because I still observed logs like:
```
Closing consumer for topic 0x6000028e0648
Closing producer for topic 0x600001210b88
```
It's because `HandlerBase::topic_` field is protected and could be accessed directly from the derived classes.
In `HandlerBase`, make `topic_` private and add two methods `topic()` and `getTopicPtr()` to get the reference to the string and the shared pointer. `getTopicPtr()` should only be called when being passed to `MessageImpl::setTopicName`.

Fix topic name is shown as a pointer rather than string

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/MessageImpl.h
lib/MultiTopicsConsumerImpl.cc
lib/MultiTopicsConsumerImpl.h
tests/ConsumerTest.cc

The message listener thread blocks when the receiver queue of `MultiTopicsConsumerImpl` is full. As message listener threads are used by all consumers in the same `Client`, if one slow consumer blocks the listener threads, all other consuemrs can no longer receive new messages.
1. Modify `MultiTopicsConsumerImpl` to use `UnboundedBlockingQueue` to avoid blocking
2. Modify the permit update logic: Increase permit only after messages consumed from `MultiTopicsConsumerImpl`
- Add a test `testNoListenerThreadBlocking`
It's just an optimization.

Avoid blocking the message listener threads

---

dependencies.yaml

Fixes https://github.com/apache/pulsar-client-cpp/issues/327
See https://curl.se/docs/security.html

Upgrade libcurl to 8.4.0 to fix CVEs

---

lib/ConsumerImpl.h
lib/Future.h
lib/ProducerImpl.h
tests/PromiseTest.cc
tests/WaitUtils.h

There is a case that deadlock could happen for a `Future`. Assume there is a `Promise` and its `Future`.
1. Call `Future::addListener` to add a listener that tries to acquire a user-provided mutex (`lock`).
2. Thread 1: Acquire `lock` first.
3. Thread 2: Call `Promise::setValue`, the listener will be triggered first before completed. Since `lock` is held by Thread 1, the listener will be blocked.
4. Thread 1: Call `Future::addListener`, since it detects the `InternalState::completed_` is true, it will call `get` to retrieve the result and value.
Then, deadlock happens:
- Thread 1 waits for `lock` is released, and then complete `InternalState::future_`.
- Thread 2 holds `lock` but wait for `InternalState::future_` is completed.
In a real world case, if we acquire a lock before …

Fix possible deadlock of Future when adding a listener after completed

---

include/pulsar/Client.h
include/pulsar/ClientConfiguration.h
lib/Client.cc
lib/ClientConfiguration.cc
lib/ClientConfigurationImpl.h
lib/ClientImpl.cc
lib/ClientImpl.h
lib/ConnectionPool.cc
lib/ConnectionPool.h
perf/PerfConsumer.cc
perf/PerfProducer.cc
tests/LookupServiceTest.cc

Fixes #221
Support having more than 1 connection to each broker.

Added support for multiple connections to each broker

---

lib/ClientImpl.cc
lib/ClientImpl.h
lib/ConnectionPool.cc
lib/ConnectionPool.h
lib/ExecutorService.cc
lib/ExecutorService.h
lib/HandlerBase.cc
lib/HandlerBase.h
lib/ProducerImpl.cc
tests/ProducerTest.cc
tests/PulsarFriend.h

This is a catch up for https://github.com/apache/pulsar/pull/21144
When a producer or consumer reconnects, a random number will be generated as the key suffix in `ConnectionPool` to create or get the `ClientConnection` object from the pool.
https://github.com/apache/pulsar-client-cpp/blob/81cc562f7b366fad97e1b80c07ef9334a808390d/lib/ConnectionPool.cc#L75
If a new connection is created with the same producer or consumer name to the broker, the broker will respond with a  `ProducerBusy` or `ConsumerBusy` error so that the reconnection will never succeed.
- Add an overload of `ConnectionPool::getConnectionAsync` that accepts an integer parameter as the key suffix. If it's not specified, generate the random number as the suffix. In this method, choose the executor by `key suffix % size`.
- …

Fix ProducerBusy or ConsumerBusy error when configuring multiple brokers per connection

---

CMakeLists.txt
pulsar-test-service-start.sh
pulsar-test-service-stop.sh
tests/AuthBasicTest.cc
tests/AuthPluginTest.cc
tests/AuthTokenTest.cc
tests/BasicEndToEndTest.cc
tests/CMakeLists.txt
tests/ConsumerTest.cc
tests/oauth2/Oauth2Test.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/339
Currently the relative path is used in unit tests to specify the token file (`.test-token.txt`) and the credential directory (`./test-conf`). If we don't run the `pulsar-tests` binary in a subdirectory, it won't be able to read these files.
Add the macro `-DTOKEN_PATH="..." -DTEST_CONF_DIR="..."` to specify absolute paths according to the `PROJECT_SOURCE_DIR`, which is defined by CMake as the absolute path of the project directory.
```bash
cmake -B build
cmake --build build -j8
./build/tests/pulsar-tests --gtest_filter='AuthPlugin*:*testRSAEncryption:*testEncryptionFailure:*DecryptionFailedMessages'
cd build
./tests/pulsar-tests --gtest_filter='AuthPlugin*:*testRSAEncryption:*testEncryptionFailure:*DecryptionFailedMessages'
```

Use absolute path to find credential files in unit tests

---

lib/ConsumerImpl.cc
tests/BasicEndToEndTest.cc
tests/ConsumerConfigurationTest.cc
tests/ConsumerTest.cc
tests/c/c_BasicEndToEndTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/88
When `close` is called if the consumer has already called `unsubscribe` or `close`, it should not fail. See
https://github.com/apache/pulsar/blob/428c18c8d0c3d135189920740192982e11ffb2bf/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1034
Use the same close logic with Java client.
Add `testCloseAgainBeforeCloseDone` and `testCloseAfterUnsubscribe` to verify the new behaviors of `Consumer::close`.

Fix close() returns ResultAlreadyClosed after unsubscribe or close

---

lib/PartitionedProducerImpl.cc
lib/ProducerImpl.cc
lib/ProducerImpl.h
tests/CMakeLists.txt
tests/chunkdedup/ChunkDedupTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/341
When a lazy partitioned producer sends two messages, the flow is:
1. `start` is called to grab the connection via `grab()`.
2. Generate 0 as the sequence id of the 1st message.
3. Add the 1st message into the queue.
4. The connection is established, `msgSequenceGenerator_` is reset from 1 to 0.
5. When sending the 2nd message, 0 is also generated as the sequence id.
Then two messages have the same sequence id.
For lazy partitioned producers, if the internal producer is not started, sending the message in the callback of its future.
Add `ChunkDedupTest#testLazyPartitionedProducer` to verify it since only the `tests/chunkdedup/docker-compose.yml` enables the deduplication.

Fix lazy partitioned producer might send duplicated messages

---

lib/ClientConnection.cc
lib/ClientConnection.h
lib/ConnectionPool.cc
tests/ClientTest.cc
tests/PulsarFriend.h

Fixes https://github.com/apache/pulsar-client-cpp/issues/346
https://github.com/apache/pulsar-client-cpp/pull/336 changes the key of the `ClientConnection` in `ConnectionPool`, while in `ClientConnection::close`, it still passes the old key (logical address) to `ConnectionPool::remove`, which results in the connection could never be removed and destroyed until being deleted as a stale connection.
What's worse, if the key does not exist, the iterator returned by `std::map::find` will still be dereferenced, which might cause crash in some platforms. See
https://github.com/apache/pulsar-client-cpp/blob/8d32fd254e294d1fabba73aed70115a434b341ef/lib/ConnectionPool.cc#L122-L123
- Avoid dereferencing the iterator if it's invalid in `ConnectionPool::remove`.
- Store the key suffix in …

Fix crash when removing connection from the pool

---

lib/BinaryProtoLookupService.cc

Log topic lookup result to help debug lookup phrase problems, such as when an abnormal broker returns incorrect lookup results.
* Change to use LOG_INFO
* Add connection string to show the response broker
This change is a trivial rework  without any test coverage.
trivial rework

Log topic lookup result

---

lib/ClientConnection.cc
lib/ClientConnection.h
lib/ConnectionPool.cc
tests/AuthPluginTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/348
Fixes https://github.com/apache/pulsar-client-cpp/issues/349
When `close` is called in `ClientConnection`'s constructor,
`shared_from_this()` will be called, which results in a
`std::bad_weak_ptr` error. This error does not happen before
https://github.com/apache/pulsar-client-cpp/pull/317 because
`shared_from_this()` could only be called when the `producers` or
`consumers` field is not empty.
Add a `ResultException` and throw it if there is a failure in
`ClientConnection`'s constructor and catch it in
`ConnectionPool::getConnectionAsync`. Then retrieve the result and
return the failed future.
Since `close` is now always called on a constructed `ClientConnection`
object, remove the 2nd parameter.
In addition, check …

Fix bad_weak_ptr when close a ClientConnection during construction

---

lib/BatchMessageKeyBasedContainer.cc
lib/ProducerImpl.cc
tests/ProducerTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/352
https://github.com/apache/pulsar-client-cpp/pull/303 adds the flush callback to the last `OpSendMsg` instead of adding to the batch message container. However, `batchMessageAndSend` will create an `OpSendMsg` and add it to the `pendingMessagesQueue_`.
https://github.com/apache/pulsar-client-cpp/blob/7bb94f45b917ed30b5302ac93ffa1f1942fc6313/lib/ProducerImpl.cc#L384-L389
In the code above, `pendingMessagesQueue_` could never be empty and the callback will be added again by `opSendMsg->addTrackerCallback`. The 1st time it's added in `createOpSendMsg` or `createOpSendMsgs` called by `batchMessageAndSend`.
Add the callback to the last `OpSendMsg only when the batch message container is empty.
In `testFlushBatch`, replace the `flush` …

Fix the flush callback might be called repeatedly

---

.github/workflows/ci-build-binary-artifacts.yaml
.github/workflows/ci-pr-validation.yaml
.gitignore
CMakeLists.txt
dependencies.yaml
pkg/mac/build-static-library.sh

https://github.com/apache/pulsar-client-cpp/pull/290 brings a regression that on macOS, Protobuf is always found with CMake Config mode, which does not set the `Protobuf_LIBRARIES` variable so that the libpulsarwithdeps.a misses the symbols of Protobuf.
When `LINK_STATIC` is ON, use CMake Module mode to find the Protobuf.
Add `build-static-library.sh` to build libraries with static dependencies and verify these libraries in PR workflow. Upload the pre-built binaries in the build workflow.

Fix Protobuf symbols not found in libpulsarwithdeps.a when building on macOS

---

build-support/stage-release.sh

It will increase some artifacts in release:
- macos-arm64.zip
- macos-x86_64.zip

Gather the macOS binaries when releasing

---

lib/CurlWrapper.h
lib/HTTPLookupService.cc

When the host of the redirect URL cannot be resolved, segmentation fault will happen:
https://github.com/apache/pulsar-client-cpp/blob/0bbc15502905d19c630d237b5e102bfb996bb098/lib/CurlWrapper.h#L173-L175
In this case, `curl` will be `nullptr`. Assigning a nullptr to a `std::string` is an undefined behavior that might cause segfault.
Check if `url` is nullptr in `CurlWrapper::get` and before assigning it to the `redirectUrl` field. Improve the
`HTTPLookupService::sendHTTPRequest` method by configuring the `maxLookupRedirects` instead of a loop and print more detailed error messages.
It's hard to mock a redirect case so I have to modify the `TopicLookupBase#internalLookupTopicAsync` in broker side and return a 307 response.
When I return a `http://unknown:8080` as the redirect URL:
``` …
```

Fix HTTP lookup segfault when the redirect host cannot be resolved

---

lib/CMakeLists.txt

The macOS pre-built binaries don't include the Version.h generated from CMake. It's because `cmake --target install` does not install the `Version.h`, which is generated by `configure_file`.
Install the `Version.h`.

Install Version.h when installing by CMakeLists

---

include/pulsar/Consumer.h
lib/Consumer.cc
lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/ConsumerImplBase.cc
lib/ConsumerImplBase.h
tests/ClientTest.cc
tests/ConsumerTest.cc
tests/PulsarAdminHelper.h

C++ client supports setting the consumer name via
`ConsumerConfiguration::setConsumerName` but it does not support getting the consumer name for a given consumer.
Add the `getConsumerName` method to `ConsumerImplBase` to get the consumer name from the config and a public method with the same name to `Consumer`.
Add `ConsumerTest.testConsumerName` to verify the consumer name is set correctly in the subscribe command.

Add the Consumer::getConsumerName API

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/MultiTopicsConsumerImpl.cc
lib/NegativeAcksTracker.cc
lib/NegativeAcksTracker.h
lib/PatternMultiTopicsConsumerImpl.cc
lib/PatternMultiTopicsConsumerImpl.h
lib/UnAckedMessageTrackerEnabled.cc
lib/UnAckedMessageTrackerEnabled.h
lib/UnAckedMessageTrackerInterface.h
tests/BasicEndToEndTest.cc
tests/ConsumerTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/358 Fixes https://github.com/apache/pulsar-client-cpp/issues/359
`async_wait` is not used correctly in some places. A callback that captures the `this` pointer or reference to `this` is passed to `async_wait`, if this object is destroyed when the callback is called, an invalid memory access will happen.
Use the following pattern in all `async_wait` calls.
```c++
std::weak_ptr<T> weakSelf{shared_from_this()};
timer_->async_wait([weakSelf](/* ... */) {
if (auto self = weakSelf.lock()) {
self->foo();
}
});
```

Fix accessing destroyed objects in the callback of async_wait

---

lib/ClientConfiguration.cc
lib/ClientConnection.cc
lib/auth/AuthOauth2.cc
run-unit-tests.sh
tests/oauth2/Oauth2Test.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/363
https://github.com/apache/pulsar-client-cpp/pull/313 has reverted the fix of https://github.com/apache/pulsar-client-cpp/pull/190, which applies the `tlsTrustCertsFilePath` config for OAuth2 authentication.
The macOS pre-built libraries are affected most because the bundled CA path is empty.
Apply the `tlsTrustCertsFilePath` for OAuth2.

Fix tlsTrustCertsFilePath config is not applied for OAuth2

---

include/pulsar/c/client_configuration.h
lib/c/c_ClientConfiguration.cc
tests/c/c_ClientConfigurationTest.cc

Fixes #369
The NodeJS client relies on the C API, which does not yet include the `getListener` and `setListener` methods. This means that using the NodeJS client, one is unable to choose which listener to create a client for.
Exposed `getListener` and `setListener` via the C API.
- Added test for newly exposed methods

[feat] [C API] Expose Get/Set Listener Name in C API

---

.github/workflows/ci-pr-validation.yaml
.gitmodules
CMakeLists.txt
LEGACY_BUILD.md
LegacyFindPackages.cmake
README.md
examples/CMakeLists.txt
lib/CMakeLists.txt
perf/BuildPerf.cmake
perf/LegacyBuildPerf.cmake
tests/BuildTests.cmake
tests/CMakeLists.txt
tests/LegacyBuildTests.cmake
vcpkg.json

Currently we manage dependencies by ourselves:
- When running unit tests in CI, dependencies are installed from the Debian package management tool `apt`
- When verifying macOS build, dependencies are installed from the Homebrew package manager
- When verifying Windows build, dependencies are installed via vcpkg but no versions are specified
- When building pre-built binaries to release, dependencies are installed by scripts under `pkg/` directories. These scripts download the source code according to `dependencies.yaml` and build
It makes the pre-built binaries never tested except for the simple manual tests when voting for a new release. As a result, regression like https://github.com/apache/pulsar-client-cpp/issues/363 could happen.
This patch aims at integrating vcpkg to manage …

Integrate vcpkg to manage dependencies for all platforms

---

include/pulsar/ClientConfiguration.h
lib/ClientConfiguration.cc
lib/ClientConfigurationImpl.h
lib/ClientConnection.cc
lib/ClientConnection.h
tests/ConsumerTest.cc

#8957 was added incorrectly and it was not supporting SNI routing for CPP client library.
This PR adds support of SNI roting to Pulsar CPP client library and allows users to connect with Pulsar broker using SNI Proxy.
User can configure Pulsar client lib to use SNI routing and proxy by adding below configuration
```
const std::string lookupUrl = "pulsar+ssl://broker-url:6651";
const std::string proxyUrl = "pulsar+ssl://sni-proxy-url:6651";
const std::string topicName = "persistent://pulsar/stg-use1/ns1/t1";
const std::string certFile = "/client-cert.pem";
const std::string keyFile = "/client-key.pem";
const std::string trustFile = "/trust-store.pem";
ClientConfiguration conf;
conf.setUseTls(true);
conf.setTlsAllowInsecureConnection(false);
conf.setTlsTrustCertsFilePath(trustFile); …
```

[PIP-60] [Proxy-Client] Support SNI routing for Pulsar CPP client

---

lib/ClientImpl.cc
lib/LogUtils.cc
lib/LogUtils.h
tests/CustomLoggerTest.cc

I noticed that there are cases where the specified logger factory is not used. For example, if we compile and run the following code, it expects `FileLoggerFactory` to be used, but it actually uses the default `ConsoleLoggerFactory`.
```cpp
ClientConfiguration config = ClientConfiguration();
config.setLogger(new FileLoggerFactory(Logger::LEVEL_INFO, "pulsar-client-cpp.log"));
ParamMap params;
params["providerDomain"]    = "provider.foo.bar";
params["tenantDomain"]      = "tenant.foo.bar";
params["tenantService"]     = "test-service";
params["privateKey"]        = "file:///path/to/private.key";
params["keyId"]             = "0";
params["ztsUrl"]            = "https://zts.athenz.example.com:443";
AuthenticationPtr auth = AuthAthenz::create(params);
config.setAuth(auth);
Client …
```

[fix] Fix issue where custom logger setting is ignored

---

lib/PartitionedProducerImpl.cc
lib/PartitionedProducerImpl.h
lib/ProducerImpl.cc
lib/ProducerImpl.h
tests/ProducerTest.cc

Fixes #319
Already created producer should not fail after new partition producers creation failure.
`ProducerImpl`: Add an option retryOnCreationError to control whether to retry on creation error
`PartitionedProducerImpl`: Use retryOnCreationError=true to create new partition producers
- Added test for new partition producer creation failure
Bug fix only.

Retry on new partition producer creation failure

---

lib/Backoff.cc
lib/Backoff.h
lib/RoundRobinMessageRouter.cc
vcpkg.json

Master issue: https://github.com/apache/pulsar-client-cpp/issues/367
We still depends on the Boost.Random dependency on some places, which could be replaced by the C++ standard random library.
- Replace Boost.Random usages with the standard `<random>` header
- Remove the `boost-random` dependency from `vcpkg.json`

Remove the Boost.Random dependency

---

dependencies.yaml
pkg/apk/Dockerfile
pkg/deb/Dockerfile
pkg/mac/build-static-library.sh
pkg/rpm/Dockerfile

The main branch is broken because Boost is downloaded from JFrog, which now requires log in.
Switch to Github to download Boost. Since GitHub only has the Boost release since 1.81.0, upgrade the version to 1.83.0, which is also consistent with vcpkg.json.

Fix Boost source code download failure

---

lib/ConsumerImpl.cc
tests/ReaderTest.cc

Fixes #385
The reader with `StartMessageIdInclusive` enabled should be able to reads messages from the latest message ID.
- If `StartMessageIdInclusive` is enabled, the reader will seek and read the latest message in the topic.
This change added tests.
It's a bug fix

Fix `StartMessageIdInclusive` not work when reader reads from latest msg id

---

lib/TimeUtils.h
tests/BackoffTest.cc

`TimeUtils::currentTimeMillis()` is used to get the timestamp since 1970 but `high_resolution_clock` does not necessarily represent the system clock. For example, given the following code:
```c++
template <typename Clock>
inline int64_t getTimestamp() {
using namespace std::chrono;
return duration_cast<milliseconds>(Clock::now().time_since_epoch()).count();
}
int main() {
std::cout << time(nullptr) << std::endl;
std::cout << getTimestamp<std::chrono::system_clock>() << std::endl;
std::cout << getTimestamp<std::chrono::high_resolution_clock>() << std::endl;
}
```
The outputs could be:
```
1705584279
1705584279351
38566832
```
Use `std::system_clock` for `currentTimeMillis()`. Add `BackoffTest.testCurrentTimeMillis` to verify the result is similar to 1000 times of `time(nullptr)` (the …

Fix wrong TimeUtils::currentTimeMillis() implementation

---

pulsar-test-service-start.sh

Pulsar 3.1.2 introduces a regression that makes two tests fail:
- AuthPluginTest.testTlsDetectPulsarSslWithInvalidBroker (try #1)
- AuthPluginTest.testTlsDetectHttpsWithInvalidBroker (try #1)
Pin the Pulsar version to 3.1.1 until there is a new Pulsar release that fixes the regression.

Pin the Pulsar version to 3.1.1 temporarily for the regression in Pulsar

---

lib/ClientConnection.cc
lib/ClientConnection.h
lib/ClientConnectionAdaptor.h
tests/ConnectionTest.cc

When the broker failed to acquire the ownership of a namespace bundle by `LockBusyException`. It means there is another broker that has acquired the metadata store path and didn't release that path. For example:
Broker 1:
```
2024-01-24T23:35:36,626+0000 [metadata-store-10-1] WARN  org.apache.pulsar.broker.lookup.TopicLookupBase - Failed to lookup <role> for topic persistent://<tenant>/<ns>/<topic> with error org.apache.pulsar.broker.PulsarServerException: Failed to acquire ownership for namespace bundle <tenant>/<ns>/0x50000000_0x51000000
Caused by: java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$LockBusyException: Resource at /namespace/<tenant>/<ns>/0x50000000_0x51000000 is already locked
```
Broker 2:
```
2024-01-24T23:35:36,650+0000 …
```

Do not close the socket when the broker failed due to MetadataStoreException

---

lib/ProducerImpl.cc
tests/ProducerTest.cc

Current code releases the producer's pending semaphore twice when batch is off and message is too big. The unbalanced release overflows the semaphore, and subsequent sends will fail with ProducerQueueIsFull.
Remove the redundant semaphore release as the necessary release will be done in `handleFailedResult`.
This change modified a existing test and can be verified as follows:
- ProducerTest.testMaxMessageSize
Bug fix.

Fix an unbalanced release of the producer's pending semaphore

---

lib/ClientConnection.cc
tests/extensibleLM/ExtensibleLoadManagerTest.cc

The `apachepulsar/pulsar:latest` image was upgraded to 3.2.0 recently, which results the following failed tests:
- ExtensibleLoadManagerTest: there are no more lookup requests after namespace unload
- ClientTest.testWrongListener: the lookup error message from broker does not contain the exception type

Fix broken main branch after Pulsar image was upgraded to 3.2.0

---

lib/ClientConnection.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/398
There is an implicit requirement for the `async_handshake` API that before it's done, the `socket` and `ssl::stream` objects must exist. Otherwise segmenatation fault might happen.
Capture `socket_` and `tlsSocket_` in the handshake callback. It can be verified by modifying the code according to #398 and rerun the test.

Fix segmenatation fault if connection is closed during handshake

---

lib/ClientConnection.cc
lib/ClientConnectionAdaptor.h
lib/ClientImpl.cc
lib/ClientImpl.h
lib/ConsumerImpl.cc
lib/Future.h
lib/HandlerBase.cc
lib/HandlerBase.h
lib/ProducerImpl.cc
lib/ResultUtils.h
tests/ClientTest.cc
tests/MockClientImpl.h

Fixes https://github.com/apache/pulsar-client-cpp/issues/391
When `connectionFailed` is called, no matter if the result is retryable the creation of producer or consumer will fail without retry.
Check if the result is retryable in `connectionFailed` for `ProducerImpl` and `ConsumerImpl` and only fail for non-retryable errors or the timeout error. Register another timer in `HandlerBase` to propagate the timeout error to `connectionFailed`.
Add `testRetryUntilSucceed`, `testRetryTimeout`, `testNoRetry` to verify client could retry according to the result returned by `ClientImpl::getConnection`.

Fix creating producer or consumer is not retried for connection failure

---

lib/ConsumerImpl.cc
tests/DeadLetterQueueTest.cc

https://github.com/apache/pulsar-client-node/issues/366
- Disable batch send for dlq producer.
- Add logic to verify that messages are not batched in DeadLetterQueueTest

Disable batch send for dlq producer.

---

lib/BinaryProtoLookupService.cc
lib/BinaryProtoLookupService.h
lib/ClientConnection.cc
lib/ClientConnection.h
lib/ClientImpl.cc
lib/ClientImpl.h
lib/HTTPLookupService.cc
lib/HTTPLookupService.h
lib/HandlerBase.cc
lib/HandlerBase.h
lib/LookupService.h
lib/ProducerImpl.cc
lib/RetryableLookupService.h
lib/ServiceNameResolver.h
proto/PulsarApi.proto
run-unit-tests.sh
tests/ClientTest.cc
tests/LookupServiceTest.cc
tests/MockClientImpl.h
tests/PulsarFriend.h
tests/blue-green/docker-compose.yml
tests/extensibleLM/ExtensibleLoadManagerTest.cc

Master Issue: https://github.com/apache/pulsar/issues/16551
Support blue-green migration pip-188 for cpp client
- added blue-green client logic 
- register the producer instance in the producers map before sending produce creation command. This is required since broker could send topic migration command in the middle of creating the producer.
Updated the exisiting extensibleLB test to cover the migration logic.

[feat] PIP-188 Support blue-green migration

---

.github/workflows/ci-pr-validation.yaml
lib/NamespaceName.cc
lib/NamespaceName.h
lib/TopicName.cc
lib/TopicName.h

When I built with Clang and C++20, there were the following errors:
> ISO C++20 considers use of overloaded operator '==' (with operand types 'pulsar::NamespaceName' and 'pulsar::NamespaceName') to be ambiguous despite there being a unique best viable function [-Werror,-Wambiguous-reversed-operator]
See the detailed answer here: https://stackoverflow.com/questions/60386792/c20-comparison-warning-about-ambiguous-reversed-operator
Make the member functions of `operator=` const in `TopicName` and `NamespaceName` and add a workflow to cover this case.

Fix the incompatibility with Clang and C++20

---

lib/ClientConnection.cc
lib/ConnectionPool.cc
lib/ConnectionPool.h

Context: https://github.com/apache/pulsar/pull/22085/files#r1497008116
Currently, the connection pool key does not include physicalAddress (currently logicalAddress + keySuffix). This can be a problem when the same logicalAddresses are in the migrated(green) cluster. (the connection pool will return the connection to the old(blue) cluster)
Add physicalAddress as part of the connection pool key
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*

[improve] add physicalAddress as part of connection pool key

---

.github/workflows/ci-pr-validation.yaml

The `clang-format` tool on `ubuntu:22.04` runner was upgraded to 14 recently, whose rule is slightly different from 11.
Use clang-format-action for code format check and specify the version to 11.

[CI] Pin the clang-format version to 11

---

lib/MultiTopicsConsumerImpl.cc
tests/BasicEndToEndTest.cc

Fixes #88
https://github.com/apache/pulsar-client-cpp/pull/338 fixed `ConsumerImpl::closeAsync` so that closing after it was already closed or unsubscribed returns `ResultOk` instead of `ResultAlreadyClosed`. However, `MultiTopicsConsumerImpl::closeAsync` still returns `ResultAlreadyClosed`. This seems to be a change omission.

[fix] Change return code of MultiTopicsConsumerImpl::closeAsync after unsubscribe or close

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
lib/Synchronized.h
tests/ReaderTest.cc

See https://github.com/apache/pulsar-client-python/issues/199
There is a race condition when `hasMessageAvailable` is called after `seek` if the start message ID of `Reader` is earliest.
In `ConsumerImpl::hasMessageAvailableAsync`, if the connection is not established at the moment, `lastDequedMessageId_` will be `earliest` because no message is received. Since `lastMessageIdInBroker_` is also `earliest`, `getLastMessageIdAsync` will be called and then it comes at
https://github.com/apache/pulsar-client-cpp/blob/e2cacb7dfb57b6d059b49fead2e1611548ff89b0/lib/ConsumerImpl.cc#L1554
However, before `getLastMessageIdAsync` is called, `messageId` was `earliest` because `lastDequedMessageId_` and `startMessageId_` were both `earliest`. However, when the callback is called, the `startMessageId_` …

Fix hasMessageAvailable might return true after seeking to latest

---

.github/workflows/ci-pr-validation.yaml

See https://github.com/apache/pulsar-client-cpp/actions/runs/8276076995/job/22644077705
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
```
`brew install` failed because the wireshark dependency depends on
python@3.12 and it failed at `brew link`.
Remove the existing binaries that might conflict.

Fix broken wireshark build workflow on macOS 

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
tests/ReaderTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/420
It's a catch-up for https://github.com/apache/pulsar/pull/22363

Fix wrong results of hasMessageAvailable and readNext after seeking by timestamp

---

lib/MultiTopicsConsumerImpl.cc
lib/MultiTopicsConsumerImpl.h
lib/SynchronizedHashMap.h
tests/ConsumerSeekTest.cc
tests/ConsumerTest.cc
tests/SynchronizedHashMapTest.cc

See https://github.com/apache/pulsar-client-python/issues/213
Add a new `forEachValue` overload that allows users to count the number of rest running tasks through `SharedFuture` to `SynchronizedHashMap`. Leverage this overload in seek operations when the argument is a timestamp, or a MessageId that represents earliest or latest. When the argument is a MessageId whose `getTopicName()` method returns a correct topic name, seek on the internal consumer of that topic.
Add `testMultiTopicsSeekAll` and `testMultiTopicsSeekSingle` to `ConsumerSeekTest` to cover these cases.

Support seek operation on a multi-topics consumer

---

lib/ClientConnection.cc

Currently when `tlsTrustCertsFilePath` is not specified, default locations of CA certificates will be used. However, these paths are determined by the compile option when building OpenSSL and they are invisible to users. If the OS uses a different path, the TLS connection will fail with no helpful error message.
References:
- https://www.openssl.org/docs/man3.3/man3/X509_get_default_cert_file.html
- https://www.openssl.org/docs/man3.3/man3/SSL_CTX_set_default_verify_paths.html
- https://www.boost.org/doc/libs/1_83_0/doc/html/boost_asio/reference/ssl__context/set_default_verify_paths/overload2.html

Log the default location of trusted CA certificates when tlsTrustCertsFilePath is not specified

---

build-support/merge_archives_vcpkg.sh
lib/CMakeLists.txt
pkg/rpm/Dockerfile
pkg/rpm/SPECS/pulsar-client.spec

See https://lists.apache.org/thread/7o8hpv1gtoffvzx053wm0ss2s9xt0795, we will discard the support for CentOS 7 and old `std::string` ABI.
- Switch from `centos:7` image and GCC 4.8 to `rockylinux:8` image and GCC 8 to build RPM packages.
- Use vcpkg to install dependencies according to `vcpkg.json` (`dependencies.json` will be deprecated in future)
- Add a new script to build `libpulsarwithdeps.a` for dependencies installed by vcpkg
- Link to `libstdc++` and `libgcc_s` libraries statically
Additional, with vcpkg, OpenSSL will search `/etc/ssl/certs.pem` for the default CA certificate rather than `/usr/local/ssl/ssl/certs.pem`.

Use Rocky Linux 8 and vcpkg to build RPM packages

---

.github/workflows/ci-build-binary-artifacts.yaml

The release workflow is broken because it uses `macos-latest` runner, which is now macOS 14 Arm64, see https://github.com/actions/runner-images
```
+ pip3 install pyyaml
error: externally-managed-environment
× This environment is externally managed
```

[CI] Use macos-12 to build macOS libraries

---

include/pulsar/c/client_configuration.h
lib/c/c_ClientConfiguration.cc
tests/c/c_ClientConfigurationTest.cc

expose partitions update interval configuration to C client
expose partitions update interval configuration to C client
- Add test to cover it.

feat: expose partitions update interval configuration to C client

---

lib/ClientConnection.h
lib/HandlerBase.cc
lib/HandlerBase.h
tests/ConsumerTest.cc
tests/ConsumerTest.h

Fixes https://github.com/apache/pulsar-client-cpp/issues/436
When a consumer starts grabbing the connection, it registers a timer after the operation timeout. When that timer is expired, it will fail the connection and cancel the connection timer. However, it results a race condition that:
1. The consumer's connection is closed (e.g. the keep alive timer failed)
2. The connection timer is registered on the executor and will trigger the reconnection after 100ms
3. The connection timer is cancelled, then the reconnection won't start.
Cancel the `creationTimer_` once `HandlerBase#start` succeeded first time. Add `testReconnectWhenFirstConnectTimedOut` to cover this case.

Fix consumer might not subscribe after a reconnection

---

lib/ClientConnection.cc

Keep compatible with old boost versions.
Port boost compatible code from branch-3.4 and make minor changes for USE_ASIO.
Code from branch-3.4:
https://github.com/apache/pulsar-client-cpp/blob/1cb1bf8ba1ca1033b4a36d35514f22fcf150973a/lib/ClientConnection.cc#L171-L177
No functionality changed. Just keep the old compatible behavior.

fix: Keep compatible with old boost versions

---

lib/ConsumerImpl.cc
lib/MultiTopicsConsumerImpl.cc

Fixes #446 
We found an ack failure issue: #446 
MessageListeners can start to process messages before subscribing all child topics are completed in "multi topics" (e.g. partitioned, list, regex) cases.
If `acknowledge()` is called in messageListeners (it is very typical usage) before subscribing completion, it will fail with `AlreadyClosed` error since the state of the parent consumer is not `Ready` yet:
https://github.com/apache/pulsar-client-cpp/blob/8b2753a56579ea6cf11e26a0c5a160797518df63/lib/MultiTopicsConsumerImpl.cc#L643-L648
That results in ack holes, and finally full backlog.
* `MultiTopicsConsumerImpl`: Pause messageListeners at first by setting `startPaused` to true and resume them after subscribing all child topics are completed.
* `ConsumerImpl`: Delete unused code.
* It …

Fix ack failure on message listener in multi topics consumer

---

.github/workflows/ci-pr-validation.yaml
tests/blue-green/docker-compose.yml
tests/extensibleLM/docker-compose.yml

With the latest image, the `pulsar-init` service will fail with command line parsing.
```
picocli.CommandLine$UnmatchedArgumentException: Unmatched arguments from index 0: '
', '
', '
', '
', '
'
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unmatched arguments from index 0: '
', '
', '
', '
', '
'
at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13662)
at picocli.CommandLine$Interpreter.parse(CommandLine.java:13614)
at picocli.CommandLine$Interpreter.parse(CommandLine.java:13559)
at picocli.CommandLine$Interpreter.parse(CommandLine.java:13454)
at picocli.CommandLine.parseArgs(CommandLine.java:1552)
at org.apache.pulsar.PulsarClusterMetadataSetup.main(PulsarClusterMetadataSetup.java:227)
```

Fix the YAML format error in latest image

---

lib/ClientConfigurationImpl.h

Fixes: Default operation timeout has the wrong value (no issue entered)
The driver will timeout on all operations because the operation timeout is initialized with a literal of a too small size and when cast to `std::chrono::seconds` we end up with 0. `long long` should be used because according to https://en.cppreference.com/w/cpp/chrono/duration `std::chrono::nanoseconds` takes a type of at least 64 bits. 
Example of the problem here:
https://godbolt.org/z/o51G6xbqo
*(Please pick either of the following options)*
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads (10MB)*
- *Extended integration test for recovery after broker failure*
(Your PR needs to update docs and you will …

Fix default operation timeout

---

include/pulsar/ClientConfiguration.h
include/pulsar/c/client_configuration.h
lib/ClientConfiguration.cc
lib/ClientConfigurationImpl.h
lib/ClientConnection.cc
lib/ClientConnection.h
lib/c/c_ClientConfiguration.cc
tests/c/c_ClientConfigurationTest.cc

Expose keep alive interval for c and c++ client
Expose keep alive interval for c and c++ client

Expose keep alive interval for c and c++ client

---

lib/ClientConnection.cc
tests/AuthTokenTest.cc

When a token supplier is passed to the `AuthToken`, if exceptions are thrown from it, the application will crash immediately. A typical case is the Python wrapper might raise an exception when trying to get token.
Catch the exception in `Commands::newConnect` because the token supplier is called in it. Then convert it to `ResultAuthenticationError`. Add `testTokenSupplierException` to verify it.

Handle the exception from the token supplier

---

.github/workflows/ci-build-binary-artifacts.yaml
.github/workflows/ci-pr-validation.yaml
pkg/mac/build-static-library.sh

macOS 12 is deprecated, see https://github.com/actions/runner-images?tab=readme-ov-file#available-images

Bump macos runner image to 14

---

lib/ConsumerImpl.cc
tests/ReaderTest.cc

Fixes https://github.com/apache/pulsar-client-cpp/issues/461

Fix startMessageInclusive does not work if the 1st message is a chunked message

---

examples/CMakeLists.txt
include/pulsar/BrokerConsumerStats.h
include/pulsar/Message.h
include/pulsar/c/client_configuration.h
lib/BrokerConsumerStats.cc
lib/Message.cc
lib/c/c_ClientConfiguration.cc

Fix some compiler warnings in public headers when using with -Wextra. These warnings prevent projects using -Wextra -Werror to use pulsar client without modifications.
1. Modified public headers to fix compiler warnings
2. Add compile options "-Wextra -Wno-unused-parameter" to compile examples to help find similar issues
This change can be verified as follows:
- Add compile options "-Wextra -Wno-unused-parameter" to compile examples to help find similar issues
Only the compiler warnings have been fixed, and there is no change in functionality.

Fix some compiler warnings in public headers

---

lib/ConsumerImpl.cc
tests/ZeroQueueSizeTest.cc

If a consumer with a receiver queue size of 0 is waiting for messages using `receive` or `receiveAsync`, and the topic is unloaded or the broker is restarted, the consumer will no longer be able to receive messages. This is because `receive` and `receiveAsync` have different bugs. Both bugs are highly reproducible.
When the `receive` method of a zero queue consumer is executed, `fetchSingleMessageFromBroker` is called internally. In `fetchSingleMessageFromBroker`, the connection of the received message is compared with the connection when the flow permit was sent, and if they do not match, the message is discarded.
https://github.com/apache/pulsar-client-cpp/blob/115d64af81ae26ae73aaba7aaba36d4a9e47324c/lib/ConsumerImpl.cc#L918-L942
If the topic is unloaded or the broker is restarted …

[fix] Fix an issue where zero queue consumers are unable to receive messages after topic unloading

---

lib/PatternMultiTopicsConsumerImpl.cc

This was introduced in v3.7.0 via #447, which contained a change that attempted to fix an issue where a pre-mature ack of a message before a multi-topic subscriber was ready could have caused a crash.  To fix the original bug, all multi-topic subscriptions are started with their message listener paused. They later get un-paused once all topics are successfully subscribed and connected.  However, on a regex subscription when new topics are discovered, they also start in a paused state, and there's no mechanism to resume them.  Hence, they get stuck, and no messages for new topics will be processed.
This change adds a call to resume any new listeners after new topics are added.  The fix has been deployed to production in my company's infrastructure and has been confirmed working for a few …

Fix multi-topics-consumer new topic listeners stuck in paused state

---

lib/ClientConnection.cc

Fixes #479 
The current keepalive logic is too lenient – merely receiving ping commands can keep the connection alive.
Ignore ping command in connection keepalive logic.
This change is a trivial rework without any test coverage. It is not easy to write a test for ClientConnection but the change is simple.
Bug fix only.

fix: ignore ping command in connection keepalive logic

---

.github/workflows/ci-pr-validation.yaml
lib/HTTPLookupService.cc
lib/JsonUtils.h
lib/Schema.cc
perf/PerfConsumer.cc
perf/PerfProducer.cc
pkg/mac/build-static-library.sh
pkg/mac/vcpkg-curl-patch.diff
vcpkg.json

- openssl 3.1.4 -> 3.5.0
- zlib 1.3 -> 1.3.1
- curl 8.4.0 -> 8.13.0
Keep the `protobuf` to an old version (3.21.12) because it's the last release that supports C++11, see https://protobuf.dev/news/2022-08-03/
Keep the `asio` version not changed (1.28.2) because there are some APIs removed.

Bump curl, openssl, zlib to address CVEs

---

.github/workflows/ci-build-binary-artifacts.yaml

The 3.7.1 release is broken due to the deprecated `upload-artifact@v3` plugin: https://github.com/apache/pulsar-client-cpp/actions/runs/14699561334

[ci] Fix upload-artifact v3 is not supported

---

build-support/download-release-artifacts.py
build-support/stage-release.sh

In addition, support skipping existing downloaded or generated files.

Fix the scripts for downloading GitHub Action artifacts

---

lib/ClientImpl.cc
lib/ConsumerImpl.cc
lib/MultiTopicsConsumerImpl.cc
lib/SynchronizedHashMap.h
lib/TableViewImpl.cc
tests/SynchronizedHashMapTest.cc
tests/TableViewTest.cc
tests/extensibleLM/ExtensibleLoadManagerTest.cc

Fixes #486
The `emplace` method of `SynchronizedHashMap` adopts the same semantics as https://en.cppreference.com/w/cpp/container/map/emplace, which inserts the key-value only when the key does not exist. `TableViewImpl` leverages this method to update the key-values, so it will never succeed. In addition, this method is not thread safe because if the key exists, an iterator will be returned to the caller, then the caller could use the iterator to modify the value without any synchronization.
Add two new methods `putIfAbsent` and `put` and remove the `emplace` method.
- `putIfAbsent`: inserts the key-value only when the key does not exist and return the optional existing value
- `put`: inserts the key-value no matter if the key exists.
Then, replace the `emplace` call with `put` in …

Fix TableView's existing key-value will never be updated

---

build-support/stage-release.sh

https://github.com/apache/pulsar-client-cpp/pull/485 introduces a regression that the temporary `x86-windows-static` and `x64-windows-static` directories are not compressed.

Fix stage-release.sh does not delete the Windows temporary directories

---

lib/MultiTopicsConsumerImpl.cc
tests/MultiTopicsConsumerTest.cc

The callback in `acknowledgeCumulative` will never be called for a multi-topics consumer when the message id is invalid.
- Fail the callback with `ResultOperationNotSupported` when the topic name of the message id is invalid
- Keep the behavior the same for `acknowledge`
- Add `MultiTopicsConsumerTest.testAcknowledgeInvalidMessageId` to verify an invalid message id won't block any acknowledge method

Fix acknowledgeCumulative never returns when accepting an invalid message id for a multi-topics consumer

---

lib/ConsumerImpl.cc
lib/ConsumerImpl.h
tests/ReaderTest.cc

The computation for `compareMarkDeletePosition` is wrong that `hasSoughtByTimestamp_` should only be checked when `lastDequedMessageId_` is `earliest`, which means no messages have been received.
Additionally, reset `startMessageId_` when seeking by timestamp, otherwise, if the initial `startMessageId` of a reader is a valid message id, that message could be filtered in https://github.com/apache/pulsar-client-cpp/blob/9b86f9e2b037015cc437abc2f5f8b9475846bf95/lib/ConsumerImpl.cc#L619-L625 or https://github.com/apache/pulsar-client-cpp/blob/9b86f9e2b037015cc437abc2f5f8b9475846bf95/lib/ConsumerImpl.cc#L774-L780
Improve `testHasMessageAvailableAfterSeekTimestamp` to cover the cases above.

Fix hasMessageAvailable incorrectly returns true when read to latest after seeking by timestamp

---

.github/workflows/ci-build-binary-artifacts.yaml
pkg/apk/APKBUILD
pkg/apk/Dockerfile
pkg/apk/build-apk.sh
pkg/apk/docker-build-apk-arm64.sh

Use vcpkg to build alpine packages

---

.github/workflows/ci-pr-validation.yaml
CMakeLists.txt
lib/AckGroupingTrackerEnabled.cc
lib/AsioTimer.h
lib/ClientConnection.cc
lib/ClientConnection.h
lib/ConsumerImpl.cc
lib/ConsumerImplBase.cc
lib/ExecutorService.cc
lib/ExecutorService.h
lib/HandlerBase.cc
lib/JsonUtils.h
lib/MultiTopicsConsumerImpl.cc
lib/Murmur3_32Hash.cc
lib/NegativeAcksTracker.cc
lib/PartitionedProducerImpl.cc
lib/PatternMultiTopicsConsumerImpl.cc
lib/PeriodicTask.cc
lib/ProducerImpl.cc
lib/RetryableOperation.h
lib/SharedBuffer.h
lib/UnAckedMessageTrackerEnabled.cc
lib/checksum/crc32c_sse42.cc
lib/stats/ConsumerStatsImpl.cc
lib/stats/ConsumerStatsImpl.h
lib/stats/ProducerStatsImpl.cc
lib/stats/ProducerStatsImpl.h
tests/AuthPluginTest.cc
tests/ConsumerTest.h
vcpkg.json

Fixes https://github.com/apache/pulsar-client-cpp/issues/475
There were some breaking changes with Boost.Asio APIs so that the code base is incompatible with the latest Boost.Asio.
- Upgrade the Asio and Boost.Asio dependencies
- Support verifying build with Boost.Asio (non-default) in CI, whose version (1.88) has deprecated some APIs
- Replace deprecated (removed) APIs with the recommended new Asio APIs, including
- Replace iterator based `async_connect` method with the `async_connect` function that accepts the list of endpoints from the latest `async_resolve` method. This also simplifies the code that it no longer needs to manually retry each endpoint, which might fix the issue like https://github.com/apache/pulsar-client-cpp/issues/502
- Replace `io_service` with `io_context`
- Replace …

Adapt to latest Asio APIs (Asio 1.32 or Boost.Asio 1.88)
